### ISSUE TITLE
Performance: Active body list

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erincatto/box2d#212]
```
http://box2d.org/forum/viewtopic.php?f=4&t=7195
```

Original issue reported on code.google.com by `erinca...@gmail.com` on 26 Jun 2011 at 11:25

**Comment by louis-langholtz** [comment]
Has anyone done any testing (speed testing) of this idea? What were the results?

**Comment by metalgearsloth** [comment]
In our game we have 10k+ physics bodies at once with <100 awake at any time on a C# port of box2d. The main bottlenecks were these 2 particular areas: https://github.com/erincatto/box2d/blob/0e45a814ef961b5318c8cc0592576172b3827e1b/src/dynamics/b2_world.cpp#L424 and https://github.com/erincatto/box2d/blob/0e45a814ef961b5318c8cc0592576172b3827e1b/src/dynamics/b2_world.cpp#L561 In our case we just cached the awake bodies instead and it made it orders of magnitude faster.

**Comment by erincatto** [comment]
Optimized in version 3.0
