### ISSUE TITLE
Minimum Vertex Distance in b2PolygonShape

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erincatto/Box2D#336]
```
If the minimum distance for a vertex in a degenerate polygon is (0.5 * 
b2_linearSlop), then should the b2DistanceSquared check compare against the 
square of this value?
```

Original issue reported on code.google.com by `isaacbu...@gmail.com` on 6 Aug 2014 at 7:46

Attachments:
* [diff.patch](https://storage.googleapis.com/google-code-attachments/box2d/issue-336/comment-0/diff.patch)

**Comment by JesseTG** [comment]
Can't this be closed now?

**Comment by erincatto** [comment]
Fixed
