### ISSUE TITLE
Unused variable warnings and static analysis fixes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erincatto/Box2D#337]
```
What steps will reproduce the problem?
1. Compile in release mode or
2. Perform static analysis

What version of the product are you using? On what operating system?
Revision 313, Mac OS X 10.9.4 (Xcode 5.1)

Please provide any additional information below.
I've attached a patch.

```

Original issue reported on code.google.com by `tn0...@gmail.com` on 29 Aug 2014 at 6:47

Attachments:
* [warning_fixes.patch](https://storage.googleapis.com/google-code-attachments/box2d/issue-337/comment-0/warning_fixes.patch)

**Comment by erincatto** [comment]
I fixed some of these. There were a couple changes I disagree with.
