### ISSUE TITLE
Feature Request: Report BeginContact/EndContact for Kinematic Bodies

### ISSUE THREAD

**Issue by flyover** [erincatto/Box2D#348]
http://www.box2d.org/forum/viewtopic.php?f=3&t=5360
http://www.badlogicgames.com/forum/viewtopic.php?t=12700&p=56535
https://dashiellgough.wordpress.com/2011/09/14/box2d-enable-collisions-between-statickinematic-bodies/

**Comment by erincatto** [comment]
This rules out potential optimizations. See my comment on the pull request for another approach. Thanks.
