### ISSUE TITLE
Feature Request: OpenCL: Merging Box2D-OpenCL

### ISSUE THREAD

**Issue by kroko** [erincatto/Box2D#355]
Hello,
Do you have any plans on merging the changes, that were introduced in this Samsung repo, namely OpenCL accel https://github.com/Samsung/Box2D-OpenCL ?
As they have used v2.2.1 as basis, that would be a quite "manual merge" though. Basically just looking at what they did and implementing it on v2.3.0 with possible further improvements.
At the end of the year I'm planning a project that will use Box2D so naturally I'm interested in using "latest and greatest", so I could try to find a time to invest in this. Although main machines/everyday is OS X (ATI GPUs with OpenCL 1.2 support) I have also a dualboot *nix and MSW machine that has NVIDIA GPU with latest drivers that introduced OpenCL 1.2 (at last!), so I could test/benchmark this on all platforms and both ATI and NVIDIA.
Thoughts?

**Comment by erincatto** [comment]
It seems they have removed that repo. Anyhow, I'm currently placing readability and educational value above performance. The main educational value of Box2D should be game physics, not GPU programming.
