### ISSUE TITLE
Feature Request: C++11 and smart pointers

### ISSUE THREAD

**Issue by kroko** [erincatto/Box2D#356]
Are there any plans to switch to C++11? Box2D is so broadly used that this would definatelly affect someone somewhere :). This would introduce the possibility to use smart pointers, so no more manual reference counting and raw deletion - helps the coder - and still keep Box2D clean, without external dependencies (no need for boost lib for smart pointers any more). Or is there some specific reason why Box2D does not/is not planning to use smart pointers? Thanks.

**Comment by erincatto** [comment]
I address this in the FAQ: https://github.com/erincatto/Box2D/wiki/FAQ

Thanks, Erin

**Comment by kroko** [comment]
Sure, not using STL/algorithms and templating supposedly makes porting to other C style languages much simpler. But imho smart pointers “won’t bite”, allocating is “the same” as raw pointers, cleanup “differs”, but is so much more safe. Anyways, I made the biggest mistake - the last point of the FAQ ;) and really, your “strategy has been successful”. Thanks for the fantastic library!

**Comment by erincatto** [comment]
I've used smart pointers for physics work before. I didn't find they helped much. In my opinion, clear ownership is more important. I try to make this clear in Box2D. For example, bodies own joints. When a body is destroyed, the joints are also destroyed. A callback lets the user know the joint pointer is invalid so they can set it to null. I find this clearer than reference counts mysteriously decremented with no communication.

**Comment by louis-langholtz** [comment]
@kroko If you're interested in general updates to the Box2D code that relate to newer standards of C++ (like C++14), please take a look at [my fork of the code](https://github.com/louis-langholtz/Box2D). So far I've also avoided using smart pointers in many cases (like on returning the body or fixture pointers from their factory create methods) but I've changed the code over from using embedded node pointers to instead using standard library mechanisms like `std::list` and `std::vector`. I have also made things like range-expressions available for use in stuff like the newer ranged for loops. I won't say that using newer C++ language features is "better" but I will say that I like it more. For example, with my changes, I found it easy to experiment with using `std::map` and `std::unordered_map` to see what effect those might have with the problem demonstrated in the *Add Pair Stress Test* of the Testbed.
