### ISSUE TITLE
b2Body::SetTransform should call `SetAwake(true)`

### ISSUE THREAD

**Issue by mlogan** [erincatto/Box2D#357]
We found a bug where a sensor fixture whose body is rotated via an explicit `SetTransform` call can fall to generate an end contact event with a fixture that was previously colliding with the sensor. Calling `SetAwake(true)` in SetTransform appears to fix the issue.

Does this seem like the correct fix for this problem? If so, I can open a PR.

**Comment by erincatto** [comment]
I recommend calling SetAwake directly when calling SetTransform. Alternatively you can configure the body to never sleep. There may be cases where people don't want SetTransform to have side effects.
