### ISSUE TITLE
Variable declaration hiding problems

### ISSUE THREAD

**Issue by borisblizzard** [erincatto/Box2D#359]
I found that there are a few variable declarations within functions that shadow declarations from previous scopes.

In the following files they don't cause any problems:

**b2CollideCircle.cpp: Declaration of "separation" in line 141 hides the one in line 64**
**b2WheelJoint.cpp: Declaration of "d" in line 144 hides the one in line 106**

But if the one in this file is resolved, Box2D starts acting differently (applying impulses is much stronger):

**b2Island.cpp: Declaration of "i" in for-loop in line 315 hides the one in line 310.**

And the final one (this one was not present in 2.3.0, but introduced in 2.3.1.) makes Box2D crash at times (a "contact" variable somewhere is NULL):

**b2ContactSolver.cpp: Declaration of "i" in for-loop in line 348 hides the one in line 293.**
(I took the line numbers of this one from the current source. They are a bit different in the actual 2.3.1.)

**Comment by jseward** [comment]
Recreated when building with VS2015. Would be nice to have a clean compile with no warnings.

**Comment by erincatto** [comment]
These should be fixed. Thanks!
