### ISSUE TITLE
Potential buffer overrun in b2Polygon::Set

### ISSUE THREAD

**Issue by ola-imageform** [erincatto/Box2D#364]
We've had a case where a polygon with collinear or close to collinear vertices resulted in a buffer overrun in b2Polygon::Set, at 

hull[m] = ih;

m is never checked against b2_maxPolygonVertices. I guess the algorithm implicitly should keep m bounded, but I believe this has to do with floating point imprecision.

I realize this is from an essentially bad polygon, but at the very least I suggest a b2Assert(m < maxPolygonVertices) before that line so that when developing, you get correct debug info, which you won't after the stack frame has been overwritten.

We got this a few times on an ARM target with 'fast' floating point mode. We wasn't able to reproduce it on our desktop/x86 target, with either floating point mode.

**Comment by erincatto** [comment]
Thanks. I added the assert. If possible, please prove the input data that triggers the bug.
https://github.com/erincatto/Box2D/commit/3d6863706955f8222e3a3d7a15c158d25bf1cdcb
