### ISSUE TITLE
State of .NET wrapper for Box2D.

### ISSUE THREAD

**Issue by bryanedds** [erincatto/Box2D#365]
I looked at the source and the last change appears to be ~ 6 yrs ago.

Any word on the state of the .NET wrapper for box2d?

Despite its age, is it in a usable state?

If not, could we consider this a feature request to get the .NET wrapper up to date?

**Comment by erincatto** [comment]
Ports to other platforms are supported by the community. Anything you find in the Contributions folder was developed by the community. I recommend looking for other projects that have C# wrappers. As a start, check this page: http://box2d.org/links/
