### ISSUE TITLE
Bodies connected by joints can fall asleep even when motor is active

### ISSUE THREAD

**Issue by Sheph** [erincatto/Box2D#367]
Consider an island containing 2 bodies and 1 revolute
joint with limits. The joint has motor enabled and motor speed set
to "x". The joint reaches its limit, bodies calm down and about to go
to sleep, but just before the sleep timer reaches b2_timeToSleep user
code calls b2Joint::SetMotorSpeed(-x). Now the next world update must
move the bodies by at least b2_xxxSleepTolerance, i.e. the motor must
do this, if it won't the island will go to sleep and the reverse motor
will not work as expected. The solution is to use a variant of b2Body::SetAwake
in b2Joint::SetMotorSpeed that'll set m_sleepTime to 0 even when the body
is awake, that way we give b2_timeToSleep more seconds to the motor to
do its thing and the island will not fall asleep.

This problem is extremely hard to reproduce, but it happens. I've made a patch for my project that uses Box2D, here it is: https://gist.github.com/Sheph/094370305594ce5846b8#file-gistfile1-txt

**Comment by Lucretiel** [comment]
Can you make a pull request that can be reviewed directly?

**Comment by erincatto** [comment]
I'm inclined to detect a changing motor speed value and wake the bodies.

**Comment by erincatto** [comment]
b2Body::SetAwake now resets the sleep timer, even if the body is already awake.
https://github.com/erincatto/Box2D/commit/836c4700c67dadc1ed8a0eb1aa23f49a35c5686e
