### ISSUE TITLE
Box2D for JS

### ISSUE THREAD

**Issue by shakiba** [erincatto/Box2D#372]
I'm interested to try to manually translate Box2D to JS, with JS style API and JS specific optimizations. Can you please provide me some guide for reading the code, where should I start, what are more important and what I can escape at beginning and still have a working code.

Also can you please let me know what would be the proper license for it.

Thanks!

**Comment by Lucretiel** [comment]
Box2D is zlib licensed:

https://github.com/erincatto/Box2D/wiki/FAQ
https://en.wikipedia.org/wiki/Zlib_License

You might consider asking these guys, who are already working on such a port: https://github.com/kripken/box2d.js/

**Comment by shakiba** [comment]
@Lucretiel Thanks, but kripken/box2d.js is compiled to JS using kripken/emscripten. I have tried it before, it was complicated to use, I think it wasn't production ready.

**Comment by df257** [comment]
Have you found a solution? I want to build v2.4.1 to js.
