### ISSUE TITLE
Can not compile on Mac OS X 10

### ISSUE THREAD

**Issue by alexeyvip** [erincatto/Box2D#373]
I opened Building.txt and see this commands:
cd $BOX2DPATH/Build
cmake -DBOX2D_INSTALL=ON -DBOX2D_BUILD_SHARED=ON ..
make
make install

after "make" command i get next error:
`[ 85%] Building C object glfw/CMakeFiles/glfw.dir/window.c.o
[ 86%] Building C object glfw/CMakeFiles/glfw.dir/egl_context.c.o
/Users/alexey/Downloads/Box2D-master/Box2D/glfw/egl_context.c:53:35: error:
      unknown type name 'EGLint'; did you mean 'GLint'?
static const char* getErrorString(EGLint error)
                                  ^~~~~~
                                  GLint`

What is wrong?

**Comment by fr-animal** [comment]
+1

**Comment by richiefrost** [comment]
Still getting this issue, as well as undeclared identifiers in the same file.
Some examples are EGL_SUCCESS, EGL_NOT_INITIALIZED, etc. 
At least 20 of these errors when trying to run "make".
Building on Mac OS X 10.9.5, cmake portion of the build seemed to be ok.

**Comment by erincatto** [comment]
I have created a handmade Xcode project for Mac.
