### ISSUE TITLE
Need replace angle-bracket form to quoted form for #includes with relative paths

### ISSUE THREAD

**Issue by 1vanK** [erincatto/Box2D#382]
It is common practice for libraries. It provides an easy way to place the library as a folder to the source of own project, modify to suit your needs and it will not conflict with library in a common includes folder

**Comment by aglv** [comment]
I agree with this. The whole `#include <Box2D/XXX/YYY/ZZZ.h>` is quite odd actually: we usually see `#include "ZZZ.h"` within the same project, and when including from other projects we'd call `#include <Box2D/ZZZ.h>`. But it's a choice the dev made, and it works. And I've seen worse.

**Comment by 1vanK** [comment]
https://github.com/erincatto/Box2D/commit/71a6079b5fa717b8b56aad6a1130b74232989183
