### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by im95able** [erincatto/Box2D#384]
First of all I apologize for posting this question here. I tried posting it on Box 2d forum but I can't register on the forum because I am not getting a registration confirmation email for some reason.

My question is: Is it possible to add or remove bodies during raycast and AABB query callbacks if they are not done within the physics time step ?

Thank you in advance

**Comment by erincatto** [comment]
No, this will cause bugs because you would be removing something from the dynamic tree while it is being traversed.

**Comment by im95able** [comment]
I thought so, thank you for the information

**Comment by erincatto** [comment]
Resolved
