### ISSUE TITLE
no defines for linux in config.h

### ISSUE THREAD

**Issue by dchatterjee172** [erincatto/Box2D#386]
https://github.com/erincatto/Box2D/blob/master/Box2D/glfw/config.h
there is no defines for linux in config.h that is why we cannot build this in linux.there is always error
i think this should be added
# if defined(**linux**)
# define _GLFW_X11
# define _GLFW_GLX
# endif

**Comment by erincatto** [comment]
Old issue. I've updated glfw and changed the build system to premake.
