### ISSUE TITLE
cannot compile in linux

### ISSUE THREAD

**Issue by dchatterjee172** [erincatto/Box2D#387]
even after adding defines for linux in config.h and correcting the path of "glext.h" in "egl_platform.h" i cannot compile this on linux
In file included from /home/debajyoti/Downloads/Box2D-master/Box2D/glfw/x11_platform.h:52:0,
                 from /home/debajyoti/Downloads/Box2D-master/Box2D/glfw/internal.h:69,
                 from /home/debajyoti/Downloads/Box2D-master/Box2D/glfw/clipboard.c:27:
/home/debajyoti/Downloads/Box2D-master/Box2D/glfw/glx_platform.h:57:3: error: #error "No OpenGL entry point retrieval mechanism was enabled"
  #error "No OpenGL entry point retrieval mechanism was enabled"
   ^
make[2]: **\* [glfw/CMakeFiles/glfw.dir/clipboard.c.o] Error 1
make[1]: **\* [glfw/CMakeFiles/glfw.dir/all] Error 2
make: **\* [all] Error 2

**Comment by dchatterjee172** [comment]
i think there is major problem in the files of this folder
https://github.com/erincatto/Box2D/tree/master/Box2D/glfw

**Comment by flyover** [comment]
I have a PR (#378) that should fix the build issues for any platform supported by GLFW.  I've tested it on Ubuntu 14.04, OS X 10, Windows 7 64 bit, Windows 10 64 bit.  I'm interested to know if this works on your Linux distribution.

Provided you've set up to build GLFW, these are the instructions to build and run the Testbed on Linux and OS X.  On Windows, cmake generates a Visual Studio solution file.
```
$ mkdir Box2D/BuildLinux
$ (cd Box2D/BuildLinux && cmake .. && make && ./Testbed/Testbed)
```

**Comment by dchatterjee172** [comment]
CMake Warning (dev) at Testbed/CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /home/debajyoti/Downloads/Box2D-2767121e56629f48d3d079152ce9960dc1e26475/Box2D/Testbed/glfw

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error at Testbed/CMakeLists.txt:100 (add_executable):
  Cannot find source file:

    imgui/imgui.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx



this is the error

**Comment by flyover** [comment]
Ah, it looks like submodules are not included in ZIP files downloaded from github.  You may need to clone the project.

$ git clone https://github.com/flyover/Box2D
$ (cd Box2D && git submodule init && git submodule update --recursive)

**Comment by dchatterjee172** [comment]
worked perfectly

**Comment by flyover** [comment]
I have merged the latest upstream changes into my fork of the project.  I've verified this builds on:
Ubuntu 14.04 64bit
OS X 10.11.4 using XCode 7.3
Windows 7 64bit using VS2013
Windows 10 64bit using VS2015
All of these use the default CMake settings run from the command line.

In general, the changes are as follows:
- remove glfw, glew and imgui source copies from Box2D
- add glfw and imgui as submodules in Box2D Testbed
- use glad, part of the glfw project, instead of glew for OpenGL bindings
- use OpenGL 2.0 in Testbed for broader platform coverage
- moved Box2D/Build/Data to Box2D/Testbed/Data
- remove Box2D/Build

**Comment by erincatto** [comment]
Did you open the handmade Box2D.sln and Xcode project? CMake is not the main build platform for Box2D. It is only there to support platforms besides Visual Studio and Xcode. I do not like how CMake fills project files with custom build steps. Some time ago I switched from CMake to Premake. Then Premake lost support. So I decided I would just maintain workable project files on Visual Studio and Xcode. It seems that Premake might be making a comeback.

I may make some of these changes individually. I like glad and I agree the Build/Data folder is misplaced.

I'm still learning Git, so I'm not ready to use submodules.

I switched to using modern OpenGL and shaders because I want to learn this stuff. I don't really care about people running the testbed on every single platform. The testbed is not Box2D.

**Comment by flyover** [comment]
I did; and they both build fine, except for the win32 targets in imgui.vcproj.  They are missing the "../.." include directory.

No pressure to merge any of these changes; just wanted to let you know it builds and works on linux.  Switching to OpenGL 2 made it easier to get working on an older laptop running Ubuntu 12.

**Comment by dagostinelli** [comment]
Hi erincatto, I share your general view of how the Visual Studio generator in CMake makes the Visual Studio projects messy.  That said, I think you'd be well served to support Linux through CMake.  Your community can help you do it if you let us.  You can start by getting a Travis CI going and let us help you correct all the bugs in your cmake implementation.  

You might also enable AppVeyor to get it building your Visual Studio solution on Windows as well as the CMake builds on Windows.  With both Travis and AppVeyor going, you'll have good platform coverage.  You can even add both clang and gcc to test out both compiler options.

At present, the CMake implementation need some work.  I've pulled the code every now and then over the last couple of years as I work on my hobby projects and each time I run into a different problem with Box2D.  Just now I pulled it and glfw is conflicting with the one I'm already supplying with my project. There is a way to do a detection of glfw in CMake to avoid the conflict.  This is just a little example of something that probably ought to be fixed.

If you can at least take the position that CMake is supported, I'm sure your community will help you work out all the problems.

**Comment by dagostinelli** [comment]
Regarding submodules, my 2 cents is that they are a bad practice.  What happens if GitHub goes the way of Google Code or Freshmeat?  A library like Box2D can stand on its own and supply things that are unlikely to be already included in a distro just as Erin has already done.

**Comment by erincatto** [comment]
I've updated glfw and changed the build system to premake. I'm happy to accept a pull request for getting premake working on Linux. Caveat: I will not accept any solution that avoids using the embedded versions of other libraries. I do not want to be chasing updates to other libraries.

**Comment by erincatto** [comment]
Another thing, in general people should not rely on premake or any other community solution to link Box2D with your own project. The Box2D library is very simple and portable. I recommend people just grab the Box2D library folder (without glfw, imgui, Testbed, etc) and put it in their project. Then just add the Box2D source files to whatever build system you use manually. This is simple and avoid conflicts.

**Comment by cirosantilli** [comment]
**Ubuntu 17.04 Testbed**

https://stackoverflow.com/questions/42351640/compiling-box2d-linux/46288300#46288300

```
cd
git clone https://github.com/premake/premake-core
cd premake-core
git checkout v5.0.0-alpha12
make -f Bootstrap.mak linux

cd
git clone https://github.com/erincatto/Box2D
cd Box2D
git checkout f655c603ba9d83f07fc566d38d2654ba35739102
cd Box2D
~/premake-core/bin/release/premake5 gmake
cd Build/gmake
make
# Must be run from there because of a ttf font is at that reative path. GDB told me that. :-)
cd ../../Testbed
../Build/gmake/bin/Debug/Testbed
```

**Comment by mckaygerhard** [comment]
how retrogade are box2d, not using submodules and include avanced rendering practices into a proyect that will not need powered machines
