### ISSUE TITLE
Prismatic Joint Crash

### ISSUE THREAD

**Issue by goyalsahil** [erincatto/Box2D#393]
My program is randomly crashing after creating a prismatic joint. The problem seems particularly related to "LocalAnchorA". I am using the latest version of Box2D. 

My apology I am not providing you the specific files that you ask for when submitting a issue, since I really cannot do any research these days because of my limited brain capacity. However, I have attached a screenshot of the error shown by Xcode(version 7.2). Hope, it helps!
 
<img width="1423" alt="screen shot 2016-01-24 at 5 45 07 pm" src="https://cloud.githubusercontent.com/assets/16863664/12536155/50107d56-c2c2-11e5-99e2-c1c6ed084690.png">

**Comment by erincatto** [comment]
This indicates bodyA is not a valid pointer.
