### ISSUE TITLE
TESTBED error on xcode os x10.11

### ISSUE THREAD

**Issue by jaychen04** [erincatto/Box2D#394]
when i run on xcode , it gets this error message：OpenGL 4.1 NVIDIA-10.8.14 310.42.15f01, GLSL 4.10
Could not init GUI renderer.  how can i solve it?

**Comment by erincatto** [comment]
I have been running on Xcode 6 lately and it is working well. I'm running on a 2014 Macbook Air with Intel graphics. Perhaps your Mac is not supporting OpenGL 4.0. You can try configuring OpenGL in Main.cpp to fix it.
