### ISSUE TITLE
b2BlockAllocator is unsafe

### ISSUE THREAD

**Issue by WalkerWhite** [erincatto/Box2D#398]
I posted on this issue in the forums:

http://box2d.org/forum/viewtopic.php?f=4&t=10159

b2BlockAllocator uses static arrays for its allocation space.  While this is okay, it also references these static variables in instance methods other than the constructor, which is not okay (and violates C++ coding conventions).  As a result, there is a rare bug where the memory space for a b2World becomes corrupted when it passes across multiple compilation units.

The fix is easy and is outlined in the post on the forums.

**Comment by louis-langholtz** [comment]
The good ole [static initialization order fiasco](https://isocpp.org/wiki/faq/ctors#static-init-order) raises its head once again. Thanks for pointing this static code out!

Looks like this may be the only place that's used. I just did a quick check for that in the library code however.

Having non-constant class static member variables that have to get run-time initialized also looks thread unsafe. Some undesired scenarios that I could imagine arising:

- The table gets initialized more than once (okay no big deal);
- the one-byte sized array values get torn in by multiple threads in the midst of read modify write cycles on architectures that don't have unique memory locations for every byte;
- a thread sees s_blockSizeLookupInitialized as set before the array values have actually been all written to memory but goes merrily on its way assuming the table value it just looked up is correct.

There may be lots of other thread safety problems (posts seem to suggest never using Box2D with multiple threads) but if we can get rid of this one at the same time, that seems like an added bonus.

If nothing else, I dislike having to have the additional startup time overhead this initial assignment adds when it is unnecessary. Looking at the code, would a more attractive fix instead be to do the following?

1. move the static members from the class scope (the b2BlockAllocator.h header file) and into the top of the file scope of the b2BlockAllocator.cpp file;
2. remove the `s_blockSizeLookupInitialized` variable;
3. make the `s_blockSizes` variable constant (or constexpr if using C++11 or newer);
4. make the `s_blockSizeLookup` variable constant (or constexpr if using C++11 or newer); and,
5. write out and do the full 641 element array assignment directly to the `s_blockSizeLookup` array.

This way initialization should be done completely at compile time and the tables are constant so no runtime startup cost nor runtime modifications get done to the two remaining variables. No doubt some template meta-programming could be used instead for writing all the data out. I cringe at the obfuscation that TMP often seems to add though and would prefer the 641 entry values all written out.

**Comment by WalkerWhite** [comment]
I think 1 is important if you remain static.  The reason this hit me was (on Windows), Cocos2d links Box2d and puts it in a DLL, while the game is a separate layer above the DLL that also links against Box2d.  Because the static is in the header, this results in two different static instances of the same variable.  I found the error by watching the static pointer for the array change over the method call boundary between the game and the DLL.

I had not caught the thread issues, but you are completely right.  It seems to me that your only options are to hard code the static variable or treat everything as instance variables and eat the memory overhead.

**Comment by erincatto** [comment]
Thanks for the report. Maybe I should be more clear that Box2D is not designed to be used in a DLL or to be thread safe.

**Comment by erincatto** [comment]
I updated the FAQ: https://github.com/erincatto/Box2D/wiki/FAQ

**Comment by goyalsahil** [comment]
My apology for re-opening the thread. However, I am facing the similar issue. Additionally, tried to create the static library in Xcode but failed. I know I am a noob, but can you please help me for this?

**Comment by erincatto** [comment]
I spent some more time looking at this. This is not a [static initialization order fiasco](https://isocpp.org/wiki/faq/ctors#static-init-order). There is no problem with the order of operations in the block allocator. This is certainly a shared library (DLL) problem with static data.

Another potential issue with shared library usage is memory allocation. You have to be sure that memory allocated in the library is freed in the library.

Another issue is thread safety. Box2D was not designed for thread safety, so there is no point in making one small aspect of Box2D thread safe.

**Comment by louis-langholtz** [comment]
Putting aside whether or not these issues are real, I’d rather functionality that could be handled at compile time got done then instead of at run time.

I don’t know what’s happened to Erin’s Box2D master branch but I believe that the change I prefer (the patch) can be seen at: Comparing erincatto:master...louis-langholtz:fix/block-allocator-static-initialization · erincatto/Box2D <https://github.com/erincatto/Box2D/compare/master...louis-langholtz:fix/block-allocator-static-initialization> (which should be a comparison between what I last believed the master branch of Box2D to be with the patch applied).

If you’d like to use the patch, great. I won’t object if you don’t though.

Thanks.

**Comment by erincatto** [comment]
The cost of filling out that array is not important unless you are allocating and destroying thousands of b2BlockAllocators per second. I don't think this is a reasonable use case.

If I change the layout of the block allocator, someone will have to be very careful not to mess up that explicitly filled array. In my opinion, this is brittle code.

Thanks for the input. I think this is an important issue to be aware of. I'd be more inclined to remove all static data. However, there may be use cases where this wastes a lot of memory.
