### ISSUE TITLE
b2Contact uses runtime initialized static memory

### ISSUE THREAD

**Issue by louis-langholtz** [erincatto/Box2D#400]
Like described in issue #398 (b2BlockAllocator is unsafe), `b2Contact` similarly does runtime initialization of static data. Specifically with its use of `s_registers` and `s_initialized` static class member variables. Besides being vulnerable to races and the static initialization order fiasco, the relevant code incurs unnecessary runtime overhead.

A fix that avoids these issues is easy and is available.

**Comment by erincatto** [comment]
There is no problem with static initialization order. The original problem was someone using a DLL that had another copy of Box2D.
