### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by FacundoAcevedo** [erincatto/Box2D#402]
Hi, I'm trying to install it via pip, I'm getting this error:

> pip install box2d
> You are using pip version 7.1.0, however version 8.0.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Collecting box2d
>   Using cached Box2D-2.3b0.zip
> Installing collected packages: box2d
>   Running setup.py install for box2d
>     Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-pqkUp3/box2d/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-oImo9T-record/install-record.txt --single-version-externally-managed --compile:
>     Extracting in /tmp/tmpEk_BJz
>     Now working in /tmp/tmpEk_BJz/distribute-0.6.34
>     Building a Distribute egg in /tmp/pip-build-pqkUp3/box2d
>     Traceback (most recent call last):
>       File "setup.py", line 248, in <module>
>         scripts = scripts,
>       File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "/tmp/tmpEk_BJz/distribute-0.6.34/setuptools/dist.py", line 225, in __init__
>         _Distribution.__init__(self,attrs)
>       File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
>         self.finalize_options()
>       File "/tmp/tmpEk_BJz/distribute-0.6.34/setuptools/dist.py", line 257, in finalize_options
>         ep.require(installer=self.fetch_build_egg)
>       File "/tmp/tmpEk_BJz/distribute-0.6.34/pkg_resources.py", line 2025, in require
>         working_set.resolve(self.dist.requires(self.extras),env,installer))
>       File "/tmp/tmpEk_BJz/distribute-0.6.34/pkg_resources.py", line 2235, in requires
>         dm = self._dep_map
>       File "/tmp/tmpEk_BJz/distribute-0.6.34/pkg_resources.py", line 2464, in _dep_map
>         self.__dep_map = self._compute_dependencies()
>       File "/tmp/tmpEk_BJz/distribute-0.6.34/pkg_resources.py", line 2497, in _compute_dependencies
>         common = frozenset(reqs_for_extra(None))
>       File "/tmp/tmpEk_BJz/distribute-0.6.34/pkg_resources.py", line 2494, in reqs_for_extra
>         if req.marker_fn(override={'extra':extra}):
>       File "/tmp/tmpEk_BJz/distribute-0.6.34/_markerlib/markers.py", line 109, in marker_fn
>         return eval(compiled_marker, environment)
>       File "<environment marker>", line 1, in <module>
>     NameError: name 'sys_platform' is not defined
>     /tmp/pip-build-pqkUp3/box2d/distribute-0.6.34-py2.7.egg
>     Setuptools not found/distribute setup failed; falling back on distutils.
>      !!! Setup will likely fail. Please install distribute by running distribute_setup.py
>      Error information: Could not build the egg.
>      ---
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-2.7
>     creating build/lib.linux-x86_64-2.7/Box2D
>     copying library/Box2D/__init__.py -> build/lib.linux-x86_64-2.7/Box2D
>     copying library/Box2D/Box2D.py -> build/lib.linux-x86_64-2.7/Box2D
>     creating build/lib.linux-x86_64-2.7/Box2D/b2
>     copying library/Box2D/b2/__init__.py -> build/lib.linux-x86_64-2.7/Box2D/b2
>     running build_ext
>     building 'Box2D._Box2D' extension
>     swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
>     swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
>     Box2D/Box2D_joints.i:506: Error: Unknown SWIG preprocessor directive: Some (if this is a block of target language code, delimit it with %{ and %})
>     Box2D/Box2D_joints.i:507: Error: Unknown SWIG preprocessor directive: have (if this is a block of target language code, delimit it with %{ and %})
>     Box2D/Box2D_joints.i:526: Error: Unknown SWIG preprocessor directive: Ratio (if this is a block of target language code, delimit it with %{ and %})
>     error: command 'swig' failed with exit status 1
>     
>     ----------------------------------------
> Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-pqkUp3/box2d/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-oImo9T-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-pqkUp3/box2d
>

**Comment by erincatto** [comment]
Wrong project, try this one: https://github.com/pybox2d/pybox2d
