### ISSUE TITLE
Question about position/velocity correction.

### ISSUE THREAD

**Issue by shakiba** [erincatto/Box2D#404]
@erincatto Is there any reason that position/velocity corrections are not attached to body (similar to sweep)? Or in other words, is there any case where a body can have more than one position/velocity correction value, for example being part of more than one island?

Thanks in advance!

**Comment by erincatto** [comment]
Islands are implemented so that all interacting bodies belong to a single island. Different islands do not interact.

**Comment by shakiba** [comment]
@erincatto Thanks! I have almost finished rewriting/porting Box2D to JS. Some examples and details are still remained, and I'm not sure CCD is working as expected. I will send you a private review soon.

**Comment by shakiba** [comment]
@erincatto It needs further optimization but works: https://github.com/shakiba/planck.js
