### ISSUE TITLE
chain shape debug drawing enhancements

### ISSUE THREAD

**Issue by rmsmith** [erincatto/Box2D#406]
Hello,  I am using a lot of chain shapes, and I have made a few modifications to improve the debug drawing:

1.  The current logic in `b2World::DrawShape` draws each vertex using a call to `DrawCircle`.  I was able to significantly improve the performance of chain shape debug drawing by adding a `DrawPoint` method to `b2Draw` and using that instead.

2.  The current logic does not draw the last vertex in the chain (but it draws the first one).  It is a one-liner fix to draw the last vertex also.

3.  The current logic does not draw the ghost vertices.  With the change to `DrawPoint` for the regular vertices, I chose to use a call to `DrawCircle` for the ghost vertices.  Thus if a ghost vertex and a regular vertex are coincident, you get a nice point inside of a circle.  This was quite handy for me to debug ghost vertex issues.

I would be happy to submit a small patch for this, but I have read the README which says you're not taking pull requests, so I opened this issue instead.

cheers,

**Comment by erincatto** [comment]
Implemented. Thanks for the report!
