### ISSUE TITLE
Mistake in commit e734e0f?

### ISSUE THREAD

**Issue by louis-langholtz** [erincatto/Box2D#407]
Not sure my notes in the [commit](https://github.com/erincatto/Box2D/commit/e734e0f53a12c5551076ba8d8feb960d0d0be706) are noticeable enough so additionally filing this issue. Seems like the added preprocessor conditional lines haven't all been in the correct locations and may adversely effect contact solver behavior. Hoping to get Erin to read my notes and confirm that there is no issue. Thanks!

**Comment by erincatto** [comment]
Thanks. I will fix this.

It's almost like compiler writers don't want us to write error checking code.

**Comment by erincatto** [comment]
Fixed
