### ISSUE TITLE
Recent commits introduce nullptr (a C++11 dependency?)

### ISSUE THREAD

**Issue by JoshuaGrams** [erincatto/Box2D#409]
I was compiling on an old version of gcc and noticed that these two recent commits use `nullptr` instead of `NULL` as is used everywhere else in the code.  Was that intentional?

https://github.com/erincatto/Box2D/commit/1ed97869bdcba0c562cff47dab73d1c01ec3f85a
https://github.com/erincatto/Box2D/commit/76fe384b25d3018299edc0bb8356948fa393d514

**Comment by erincatto** [comment]
Yes, I would like to use override too. Does this cause a problem for you?

**Comment by JoshuaGrams** [comment]
I'll upgrade: it should be fine. I was just attempting a build on a box that I hadn't touched in several years. Thanks.
