### ISSUE TITLE
Open GL related error

### ISSUE THREAD

**Issue by Eulerianial** [erincatto/Box2D#410]
Hello,

I am seeing following error on Ubuntu 14.04:
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenGL.cmake:161 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:28 (find_package)

Any tips?

**Comment by Eulerianial** [comment]
After installing the OpenGL related library, the build progressed and now I see following error:

You have called ADD_LIBRARY for library glfw without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configuring done
CMake Error at Testbed/CMakeLists.txt:84 (add_executable):
  Cannot find source file:
    Framework/imgui.h
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
-- Build files have been written to: /home/vijay/Box2D/Box2D/Box2D/Build

**Comment by gaNanteng** [comment]
I get the same error message "You have called ADD_LIBRARY for library glfw without any source files. This typically indicates a problem with your CMakeLists.txt file", have you found the solution of this issue?

**Comment by nburn42** [comment]
Same problem here

**Comment by DaftSpline** [comment]
I am having the same issue as well.

**Comment by sschweig** [comment]
Had this same issue. I applied fixes to two CMakeLists and successfully compiled. My fork contains the fixes, however the result is lightly tested (it's 2:30am here) but Box2D includes successfully.

**Comment by krogank9** [comment]
I'm getting the same problem

**Comment by tomasian** [comment]
Same.

**Comment by RKopczynski** [comment]
@sschweig 
Thanks bro! Now cmake works fine :)

**Comment by richardeigenmann** [comment]
For reference: Add the lines below into the file Box2D/glfw/CMakeLists.txt file at line 39, pushing down the endif():
else()
    set(glfw_HEADERS ${common_HEADERS} win32_platform.h win32_tls.h winmm_joystick.h)
    set(glfw_SOURCES ${common_SOURCES} win32_init.c win32_monitor.c win32_time.c win32_tls.c win32_window.c winmm_joystick.c)

**Comment by erincatto** [comment]
Box2D is now using Premake5. I'm looking for help to get Premake5 working on Linux.
