### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by schwmi** [erincatto/Box2D#411]
Currently, there exists just an outdated podspec in the cocoapods main repo, which points to the google svn trunk https://github.com/CocoaPods/Specs/blob/master/Specs/box2d/2.3.0/box2d.podspec.json

It would be great if this could be updated. If you want I can make a PR for this.

**Comment by purepure** [comment]
That is really cool guy. Hope you can update pod spec

Thank

**Comment by joaomvfsantos** [comment]
I think the person who created the podspec is not the same as the creator of this library. Related to #408

**Comment by erincatto** [comment]
Wrong project.

**Comment by purepure** [comment]
@schwmi Hi!
I am also stuck in there because of cocoapod issue. Do you know how to integrate this into xcode?. Please guide me through

Thank!
