### ISSUE TITLE
Included MSVC imgui project will not compile

### ISSUE THREAD

**Issue by ShardTheBroken** [erincatto/Box2D#413]
In the included MSVC14 solution in "Box2D/Build/vs2015", the imgui project will not compile for the Win32 configuration as the additional include directories are missing.

**Comment by ShardTheBroken** [comment]
I tried creating a branch and a pull request before I realised git doesn't let just anyone submit a pull request, all that needs to happen is "../.." needs added to the Win32 configs' Additional Include Directories. I realise it's a very small, easily fixed issue, but I think it would be great if the solution worked straight "out of the box".

**Comment by erincatto** [comment]
Thanks for the report. Fixed.
