### ISSUE TITLE
nullptr problem

### ISSUE THREAD

**Issue by dimitrisx** [erincatto/Box2D#415]
Cloned 374664b and tried to build Box2D but I got the following compile error:

"error: ‘nullptr’ was not declared in this scope"

I then run cmake enabling c++11 (-DCMAKE_CXX_FLAGS=-std=c++11) and the problem was fixed.

**Comment by CaffeineViking** [comment]
Yes, it seems this was reported elsewhere recently too, over at issue #414. Pull request #412 seems to fix this issue, it's currently pending. Could you apply #412 and see if this fixed your problem? One search through the Box2D source shows that the patch at #412 removes the only instance of nullptr.

**Comment by erincatto** [comment]
I'm planning to use other C++11 features, such as override.
