### ISSUE TITLE
Error in manual

### ISSUE THREAD

**Issue by o-tantk** [erincatto/Box2D#421]
In example for Shape Ray Cast at page 21,
Input points are set like 3D vector.

```
b2RayCastInput input;
input.p1.Set(0.0f, 0.0f, 0.0f);
input.p2.Set(1.0f, 0.0f, 0.0f);
```

**Comment by erincatto** [comment]
https://github.com/erincatto/Box2D/commit/a235e57f5b7bb064185e161b7f2e4e192bc042e7
