### ISSUE TITLE
b2PolygonShape area calculation is zero when verts are large

### ISSUE THREAD

**Issue by MelvynMay** [erincatto/box2d#422]
When b2PolygonShape calculates the centroid 'b2PolygonShape::ComputerCentoid' where the polygon verts are large (I created a square centered on [-15000,-15000] of size [0.72,0.72]), the area is calculated as zero.

The source [https://github.com/erincatto/Box2D/blob/master/Box2D/Box2D/Collision/Shapes/b2PolygonShape.cpp] already has an #if/#endif that calculates the reference point to be inside the polygon but this is disabled by default, presumably for a minor performance improvement.  Enabling this fixes the problem by not having the reference point at the world origin.

Note that this logic is permanently implemented in the 'b2PolygonShape::ComputeMass' method so it would seem best to be consistent and permanently enable it when calculating the centroid.

**Comment by louis-langholtz** [comment]
Thanks for pointing this out. On testing the relevant code, I'm seeing issues that I believe to be what you're describing. And I agree with your recommendation.

Incidentally, I've been working on a suite of unit tests of the Box2D library using Google Test and am adding tests for this situation (along with the change you've suggested).

**Comment by erincatto** [comment]
Fixed in #609
