### ISSUE TITLE
Little mistake in Chinese manual

### ISSUE THREAD

**Issue by mythsman** [erincatto/Box2D#423]
In Chinese manual  7.2.筛选 , the sentence:

>  " 你可以使用b2Shape::GetFilterData 和b2Shape::SetFilterData来访问和设置已存在的fixture的b2FilterData结构。"

 should be replaced by:

> "你可以使用b2Fixture::GetFilterData 和b2Fixture::SetFilterData来访问和设置已存在的fixture的b2FilterData结构"

Thanks for your work.

**Comment by erincatto** [comment]
Merged pull request. Thanks!
