### ISSUE TITLE
Release new version with stable checksum

### ISSUE THREAD

**Issue by Timmmm** [erincatto/box2d#431]
Recently box2d was [removed](https://github.com/Homebrew/homebrew-core/pull/4482) from brew because [the checksum for the 2.3.1 tarball changed](https://github.com/erincatto/Box2D/issues/420). The checksum change was because of a change to Github's tarball generation. I have verified manually that there are no changes in its content.

Unfortunately brew (perhaps unwisely) relies on the tarball checksum being constant, rather than the checksum of its contents being constant, and they thought you had been hacked or something.

To fix this, would you consider making a new release, but then rather than letting Github handle the source tarball generation (or in addition to that) manually attach a source tarball to the release?

This might also be a good opportunity to do a new release since it has been a few years!

**Comment by MikeMcQuaid** [comment]
> Recently box2d was removed from brew because the checksum for the 2.3.1 tarball changed. The checksum change was because of a change to Github's tarball generation. I have verified manually that there are no changes in its content.

A Homebrew contributor created an issue about this and received no reply: https://github.com/erincatto/Box2D/issues/420

> To fix this, would you consider making a new release, but then rather than letting Github handle the source tarball generation (or in addition to that) manually attach a source tarball to the release?

GitHub archives do not change checksum randomly so this may be overkill.

**Comment by louis-langholtz** [comment]
> This might also be a good opportunity to do a new release since it has been a few years!

What sort of changes would you like to see in a new release?

I have my own fork and branches of the Box2D C++ code that I have been making changes to. But those have been changes that I've wanted. Like: doing at compile-time what had been getting done at startup-time; refactoring code towards more pure-functions; making it more run-time configurable; using C++11 capabilities (AAA, constexpr, ranged-based for loops, RVO, etc); and unit testing it (using google gtest framework). Are any of these things, changes that you'd like to see?

I don't consider my dev branch ready to be anyone's release version yet. But that's where most of my changes are. If there's interest in these changes, I will focus more on getting it release ready however.

Other people have made other kinds of changes in there own forks, but I'm less aware of those. At least one person added multithreading to the library which is also interesting to me.

**Comment by Timmmm** [comment]
> What sort of changes would you like to see in a new release?

None in particular; I just assumed some issues have been fixed.

**Comment by erincatto** [comment]
I'll make a new release after I close a few more issues. Likely it will be release 2.3.2.

**Comment by jjatria** [comment]
Not many more issues seem to have been closed since the last post on this thread, but I was wondering if you might consider releasing 2.3.2 regardless, even if it is only a minor, convenience release.

I'm trying to update a dusty package that allows Box2D to be used in Perl modules, and setting things up to build the current version (using premake5) is significantly easier than doing so for 2.3.1.

**Comment by erincatto** [comment]
Here it is: https://github.com/erincatto/box2d/releases/tag/v2.4.0

**Comment by marmichalski** [comment]
FYI: https://github.com/Homebrew/homebrew-core/pull/62133 😛
