### ISSUE TITLE
No error catching for wrong position

### ISSUE THREAD

**Issue by Randomneo** [erincatto/Box2D#432]
Create bodyDef set position 0, 0.
Create shape 50, 50.
Try create fixture.

```
b2BodyDef* bodyDef = new b2BodyDef();
bodyDef->type = b2_dynamicBody;
bodyDef->position.Set(0, 0);
body = world->CreateBody(bodyDef);

b2PolygonShape* box = new b2PolygonShape();
box->SetAsBox(50, 50);

body->CreateFixture(box, 1);
```

I'm suppose this is a problem.

With best regards, Misiura Rostislav

**Comment by erincatto** [comment]
SetAsBox is taking the width and height, not the position. This is working as intended.

**Comment by Randomneo** [comment]
bodyDef->position.Set(0, 0);
box->SetAsBox(50, 50);

I'm set center to (0, 0) and then create object with some size.
In this case objcet position is (-25, -25).
