### ISSUE TITLE
somthing about ImGUI file not there? how do i get it? im tring to install aimtux :

### ISSUE THREAD

**Issue by BrxD** [erincatto/Box2D#433]
fatal error: ../ImGUI/imgui.h: No such file or directory
 #include "../ImGUI/imgui.h"

**Comment by Spoon94** [comment]
http://blog.csdn.net/sinat_23185975/article/details/53323241

**Comment by erincatto** [comment]
Old issue. I've updated glfw and changed the build system to premake.
