### ISSUE TITLE
Infinite friction can blow away touching bodies

### ISSUE THREAD

**Issue by louis-langholtz** [erincatto/box2d#434]
To see this problem for yourself, set the first friction value in the frictions array of the `VaryingFriction` Testbed test to the floating point value for infinity (`std::numeric_limits<float>::infinity()`) then watch what happens when the leftmost square hits the first platform.

Delving into this, I discovered that the infinite friction sometimes gets multiplied by zero resulting in NaN. This in turn is passed to the `b2Clamp` function as its low and high parameter values resulting in NaNs for the body's velocity and position (see the `b2ContactSolver::SolveVelocityConstraints()` method in `b2ContactSolver.cpp`).

I changed `b2Clamp` to not bound its value by high or low if high or low was NaN. With this change, the infinite friction no longer blew away any platforms and that box simply stuck in-place *as-intended* on the first platform.

**Comment by erincatto** [comment]
I'd rather not make b2Clamp slower to support this value. Just use a large float.
