### ISSUE TITLE
How to set more than 16 categoryBits ?

### ISSUE THREAD

**Issue by Dopamine1** [erincatto/Box2D#436]
As I know, I can filter collision by setting 0x0001, 0x0002, 0x0004 ... categoryBits for each fixture 
In this case, there's only 16 categoryBits aviable.
But what if I want set unique filter rules for more than 16 fixtures?
Is there any way to do that?

**Comment by 1aam2am1** [comment]
b2ContactFilter

**Comment by erincatto** [comment]
You can modify this locally by using uint32. In my experience, most games don't need this.
