### ISSUE TITLE
C++ 11 in new version

### ISSUE THREAD

**Issue by 1vanK** [erincatto/Box2D#438]
Current version uses nullptr in single place and do not compile on platforms without C++ 11 support
```
void b2Body::DestroyFixture(b2Fixture* fixture)
{
	if (fixture == nullptr)
	{
		return;
	}
    ...
```

**Comment by 1vanK** [comment]
Can be changed to 
```
if (!fixture)
```

**Comment by erincatto** [comment]
I plan to use some C++11 features like override.

**Comment by 1vanK** [comment]
anyway ours engine (Urho3D) also will be moved to C++ 11 soon

**Comment by JesseTG** [comment]
Who still avoids C++11 anyway?
