### ISSUE TITLE
Support cocoapod

### ISSUE THREAD

**Issue by purepure** [erincatto/Box2D#440]
Firstly, this is amazing work! Thank you so much.

I am working on project (ios) and using cocoapod to integrate box2d into my project without problem since it was hosted on google source. But when you migrate to github, cocoapod no longer supported, that break my project. 
I also tried to integrate manual this library into my project but box2d always raise issue about "source not found" at #include section.

I write here to request cocoapod support or if not, please provide document to integrate with xcode.

I am new at box2dx and workflow of it so please point me out something I can work with it and xcode

Thank you!
<img width="1406" alt="screen shot 2017-02-16 at 15 06 43" src="https://cloud.githubusercontent.com/assets/3175469/23012620/9f018d96-f459-11e6-86bd-aead321c9594.png">

**Comment by erincatto** [comment]
I'm sorry, supporting external build/package systems it out of the scope of this project. Please contact the cocoapod group for support. Thank you.
