### ISSUE TITLE
Dead code in b2Distance

### ISSUE THREAD

**Issue by Genbox** [erincatto/Box2D#446]
On [this line](https://github.com/erincatto/Box2D/blob/71a6079b5fa717b8b56aad6a1130b74232989183/Box2D/Box2D/Collision/b2Distance.cpp#L515) distanceSqr1 get set, but is never used. Is that on purpose?

**Comment by erincatto** [comment]
FIxed. Thanks!
https://github.com/erincatto/Box2D/commit/e188d132012c7f9a7420092b548851011bc40c17
