### ISSUE TITLE
Vulnerability to oddity of floating-point arithmetic in b2Sweep::GetTransform

### ISSUE THREAD

**Issue by louis-langholtz** [erincatto/box2d#447]
Not sure how to clearly explain this but I have found an oddity of floating-point arithmetic that can crop up in the `b2Sweep::GetTransform` method.

Basically, the problem is that in floating point arithmetic one can't rely on the normal mathematical relationship that for any real number `a` and any real number `beta` that's between 0 and 1, that `a * (1 - beta) + a * beta == a`. I came across this after seeing some unexpected results from the `DumpShell` Test. Here's a snippet of C++ code that shows this using Google Test:

    TEST(float, beta)
    {
        float a = 2.587699890136719e-02f; // from x position value set in DumpShell.h
        float beta = 0.0866042823f; // from debugging the unexpected
        float coefficient0 = 1 - beta;
        float coefficient1 = beta;
        ASSERT_EQ(coefficient0 + coefficient1, 1.0f);
        EXPECT_NE(a * coefficient0 + a * coefficient1, a);
    }

This assumption shows up in the `b2Sweep::GetTransform` method. The result of this can be that: 

1. the translation portion of the returned transform (`p`) may not be equal to `c0` for a sweep having a `c0 == c` (and a `localCenter` of `b2Vec2(0, 0)`) ; or
2. the rotational portion of the returned transform (`q`) may not be equal to `a0` for a sweep having `a0 == a`.

This potentially odd result is avoided by rewriting the `b2Sweep::GetTransform` instead as:

    inline void b2Sweep::GetTransform(b2Transform* xf, float32 beta) const
    {
        xf->p = c0 + (c - c0) * beta;
        float32 angle = a0 + (a - a0) * beta;
        xf->q.Set(angle);
        
        // Shift to origin
        xf->p -= b2Mul(xf->q, localCenter);
    }

I have not confirmed whether this algebraic re-ordering introduces other potentially surprising results but I have confirmed that this re-ordering does avoid the originally described odd result shown in the Google Test code. If anyone knows of other places where floating point issues can arise that can be rewritten (seemingly without introducing very much additional computational overhead), I'd very much like to read about these.

**Comment by erincatto** [comment]
I was using the form that generalizes for more than two barycentric coordinates. In this case of just two barycentric coordinates we get a nice optimization and a minor accuracy improvement.

Fixed in #610

**Comment by erincatto** [comment]
Apparently this wasn't that great a of fix. See
https://fgiesen.wordpress.com/2012/08/15/linear-interpolation-past-present-and-future/

**Comment by erincatto** [comment]
Reverted in #655
