### ISSUE TITLE
Static body with contact, does not go to sleep after contacted dynamic body is destroyed.

### ISSUE THREAD

**Issue by luisgrimaldo** [erincatto/box2d#450]
Repro:
Create a dynamic body that is moving and making continuous contact with a static body. While the movement is happening, destroy the dynamic body (while the world is unlocked). This will leave the static body in an indefinitely awaken state.

Possible solution:
Maybe a solution could be somehow flagging the fixtures that were in contact with the destroyed body for re-evaluation of contacts or something like that.

**Comment by erincatto** [comment]
Fixed #614
