### ISSUE TITLE
Rope dead-code?

### ISSUE THREAD

**Issue by louis-langholtz** [erincatto/Box2D#451]
In [Box2D/Box2D/Box2D](https://github.com/erincatto/Box2D/tree/master/Box2D/Box2D) is the `Rope` folder. It has two files in it:

1. [b2Rope.cpp](https://github.com/erincatto/Box2D/blob/master/Box2D/Box2D/Rope/b2Rope.cpp), and
2. [b2Rope.h](https://github.com/erincatto/Box2D/blob/master/Box2D/Box2D/Rope/b2Rope.h).

These don't seem to serve any purpose at the moment however as I believe rope functionality is provided through the `b2RopeJoint` class. So I'm basically wondering if the Rope folder and its contents should be removed or if there's a purpose to them.

Thanks!

**Comment by 1vanK** [comment]
Another ThirdParty libs also contains not exported in Urho code. For example ThirdParty\Bullet\src\BulletSoftBody\
I think it is not problem. Users can use these parts themselves, if they need

**Comment by erincatto** [comment]
Actually b2Rope is the main library. The other stuff is just fluff.

Just kidding, but the rope stuff is there because I was experimenting with a 2D cloth simulation. No need to worry about it.

**Comment by louis-langholtz** [comment]
Cloth simulation?? Cool beans! ;)

Thank you for the clarification.

**Comment by 1vanK** [comment]
Oh, I'm sorry, I made a mistake with the repository X)) I think qustion in my repo
