### ISSUE TITLE
Testbed Assertion

### ISSUE THREAD

**Issue by blakat** [erincatto/Box2D#452]
Terminal output
![screenshot_15](https://cloud.githubusercontent.com/assets/3877291/26135115/58d4a344-3a81-11e7-859e-41e6d66c86c2.png)

Raw data
OpenGL 4.5.0 NVIDIA 375.66, GLSL 4.50 NVIDIA
Testbed: ../../imgui/imgui_draw.cpp:1171: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `0' failed.
Aborted (core dumped)

Note: I built using a Makefile generated by premake5. Solutions?

**Comment by erincatto** [comment]
Ensure your working directory is the Testbed folder.
See: https://github.com/erincatto/Box2D/blob/master/Box2D/Building.txt
