### ISSUE TITLE
Issues with Visual Studio 2017

### ISSUE THREAD

**Issue by MajorMango** [erincatto/Box2D#459]
After creating the Build folder with remake5, visual studio have problems to build the Projekt, caused by casting errors in in the header files. My Visual studio is running on default instruktions.

**Comment by Umkerius** [comment]
In addition to this, a have compiler warning:
"cl : warning D9002: unknown parameter -std=c++11"

**Comment by afamai** [comment]
I am also having issues setting up Box2D for my projects in VS2017. 
Here are the steps I used to setup:

1. Create the build with premake5
2. Open up the Box2D.sln file and build the Box2D project.
3. Open up a new Visual Studio 2017 project
4. Set the Additional Include Directory to the Box2D header folder
5. Set the Additional Library Directories (under linker) to the folder that contains the lib file (Box2D.lib)
6. Set the Additional Dependencies to Box2D.lib
7. Add the HelloWorld.cpp to the project under Source files
8. Build

And when I try to build the project i receive the following errors.

>HelloWorld.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall b2PolygonShape::ComputeMass(struct b2MassData *,float)const " (?ComputeMass@b2PolygonShape@@UBEXPAUb2MassData@@M@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall b2PolygonShape::ComputeAABB(struct b2AABB *,struct b2Transform const &,int)const " (?ComputeAABB@b2PolygonShape@@UBEXPAUb2AABB@@ABUb2Transform@@H@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall b2PolygonShape::RayCast(struct b2RayCastOutput *,struct b2RayCastInput const &,struct b2Transform const &,int)const " (?RayCast@b2PolygonShape@@UBE_NPAUb2RayCastOutput@@ABUb2RayCastInput@@ABUb2Transform@@H@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall b2PolygonShape::TestPoint(struct b2Transform const &,struct b2Vec2 const &)const " (?TestPoint@b2PolygonShape@@UBE_NABUb2Transform@@ABUb2Vec2@@@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: void __thiscall b2PolygonShape::SetAsBox(float,float)" (?SetAsBox@b2PolygonShape@@QAEXMM@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall b2PolygonShape::GetChildCount(void)const " (?GetChildCount@b2PolygonShape@@UBEHXZ)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: virtual class b2Shape * __thiscall b2PolygonShape::Clone(class b2BlockAllocator *)const " (?Clone@b2PolygonShape@@UBEPAVb2Shape@@PAVb2BlockAllocator@@@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: class b2Fixture * __thiscall b2Body::CreateFixture(struct b2FixtureDef const *)" (?CreateFixture@b2Body@@QAEPAVb2Fixture@@PBUb2FixtureDef@@@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: class b2Fixture * __thiscall b2Body::CreateFixture(class b2Shape const *,float)" (?CreateFixture@b2Body@@QAEPAVb2Fixture@@PBVb2Shape@@M@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: void __thiscall b2World::Step(float,int,int)" (?Step@b2World@@QAEXMHH@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: class b2Body * __thiscall b2World::CreateBody(struct b2BodyDef const *)" (?CreateBody@b2World@@QAEPAVb2Body@@PBUb2BodyDef@@@Z)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: __thiscall b2World::~b2World(void)" (??1b2World@@QAE@XZ)
>HelloWorld.obj : error LNK2001: unresolved external symbol "public: __thiscall b2World::b2World(struct b2Vec2 const &)" (??0b2World@@QAE@ABUb2Vec2@@@Z)
>MSVCRT.lib(exe_winmain.obj) : error LNK2001: unresolved external symbol _WinMain@16

**Comment by afamai** [comment]
I figured out why I was getting this error. Apparently Box2D was configured to build in x64 and I was building my project in x86.

**Comment by erincatto** [comment]
Thanks, this should be fixed.
