### ISSUE TITLE
Creating Many Particles at Once

### ISSUE THREAD

**Issue by xgibbousx** [erincatto/Box2D#461]
I have created a simple particle system with Box2D that instantiates multiple physics bodies at once or in a tight interval.  On slower computers, there is a large delay while trying to create say 20 bodies at once or in a tight interval.  It seems that body creation is expensive.

What would you recommend in order for me to create multiple bodies at once in Box2D to be used for a particle system?

Is there a way to pre-create the bodies and then emit them once I need them?

Thank you!

**Comment by erincatto** [comment]
It will be slow if you create them all overlapped. This becomes an order N * N problem.

**Comment by xgibbousx** [comment]
Yes, I have done some deeper debugging (using debug breakpoint timing) and found that the slowdown is actually due to me constantly re-compiling a lighting shader for each particle that is instantiated.  I now have to figure out a way to compile that shader once during game load and then reuse it...  Should be an interesting exercise.

Box2D is actually impressively performant.  Once I removed the lighting shader (just for testing) all the physics bodies instantiated with zero delay.  I am now looking forward to splattering physics particles everywhere once I solve the shader issue above.

Thank you Erin for your awesome physics library.  I really love using it.
