### ISSUE TITLE
b2Body moves when b2Body it is currently making contact with replaces its fixture with the same fixture.

### ISSUE THREAD

**Issue by luisgrimaldo** [erincatto/Box2D#463]
Description:
We have a static body called "ground" (a ramp), and a car (from Car.h) on top of it, due to friction and the car braking, the car will rest on the ramp until it is no longer awake. At that point, I destroy the fixture of the ramp, and then add the same fixture that was just destroyed back to the ramp (in my project, i am actually modifying this fixture, but to reproduce this replacing it with the same fixture will be enough). After re-adding the fixture, the car is awaken (as it used to have contact with the old fixture), However, the body moves very slightly right after the fixture replacement. This seems like a bug to me, as the body should stay still as nothing has really changed.

Please let me know if this is actually expected or if it is a bug, if this is expected, I would appreciate a work around to prevent the car from moving after the fixture replacement (as this could have serious consequences in my project).

Repro steps:
To quickly debug this, you can open the testbed and replace the Tile example with the following code, where you can just execute the testbed/select Tile and then press W when you need to simulate the fixture replacement. You will see that the object (very slightly moves, it is more obvious in my project than in this demo, but if you pay close attention you will see it move)

```
class Tiles : public Test
{
public:

	b2Body *ground = nullptr;
	b2Fixture *groundFixture = nullptr;
	b2FixtureDef groundFixtureDef;
	b2ChainShape groundShape;

	b2Body *m_car = nullptr;
	b2WheelJoint *m_spring1 = nullptr;
	b2WheelJoint *m_spring2 = nullptr;

	bool replace = false;

	Tiles()
	{
		float32 m_hz = 4.0f;
		float32 m_zeta = 0.7f;

		{
			b2Vec2 pts[] = {
				b2Vec2(-5, -5),
				b2Vec2(5, 0),
				b2Vec2(5, -5)
			};

			groundShape.CreateLoop(pts, 3);
			b2BodyDef groundDef;
			ground = m_world->CreateBody(&groundDef);

			groundFixtureDef.shape = &groundShape;
			groundFixtureDef.friction = 0.65;
			groundFixture = ground->CreateFixture(&groundFixtureDef);
		}

		{
			b2PolygonShape chassis;
			b2Vec2 vertices[8];
			vertices[0].Set(-1.5f, -0.5f);
			vertices[1].Set(1.5f, -0.5f);
			vertices[2].Set(1.5f, 0.0f);
			vertices[3].Set(0.0f, 1.96f);
			vertices[4].Set(-1.15f, 1.96f);
			vertices[5].Set(-1.5f, 0.2f);
			chassis.Set(vertices, 6);

			b2CircleShape circle;
			circle.m_radius = 0.4f;

			b2BodyDef bd;
			bd.type = b2_dynamicBody;
			bd.position.Set(0.0f, 1.0f);
			m_car = m_world->CreateBody(&bd);
			m_car->CreateFixture(&chassis, 1.0f);

			b2FixtureDef fd;
			fd.shape = &circle;
			fd.density = 1.0f;
			fd.friction = 0.9f;

			bd.position.Set(-1.0f, 0.35f);
			b2Body *m_wheel1 = m_world->CreateBody(&bd);
			m_wheel1->CreateFixture(&fd);

			bd.position.Set(1.0f, 0.4f);
			b2Body *m_wheel2 = m_world->CreateBody(&bd);
			m_wheel2->CreateFixture(&fd);

			b2WheelJointDef jd;
			b2Vec2 axis(0.0f, 1.0f);

			jd.Initialize(m_car, m_wheel1, m_wheel1->GetPosition(), axis);
			jd.motorSpeed = 0.0f;
			jd.maxMotorTorque = 20.0f;
			jd.enableMotor = true;
			jd.frequencyHz = m_hz;
			jd.dampingRatio = m_zeta;
			m_spring1 = (b2WheelJoint*)m_world->CreateJoint(&jd);

			jd.Initialize(m_car, m_wheel2, m_wheel2->GetPosition(), axis);
			jd.motorSpeed = 0.0f;
			jd.maxMotorTorque = 10.0f;
			jd.enableMotor = false;
			jd.frequencyHz = m_hz;
			jd.dampingRatio = m_zeta;
			m_spring2 = (b2WheelJoint*)m_world->CreateJoint(&jd);

			m_car->SetTransform(b2Vec2(2, -0.5), M_PI / 4);
		}
	}

	void Step(Settings* settings)
	{
		if(replace)
		{
			ground->DestroyFixture(groundFixture);
			ground->CreateFixture(&groundFixtureDef);
			replace = false;
		}

		b2Transform xf = m_car->GetTransform();
		g_debugDraw.DrawString(5, m_textLine, "press W to replace the ground fixture");

		Test::Step(settings);
	}

	void Keyboard(int key)
	{
		switch (key)
		{
			case GLFW_KEY_A:
				m_spring1->SetMotorSpeed(50);
				break;

			case GLFW_KEY_S:
				m_spring1->SetMotorSpeed(0.0f);
				break;

			case GLFW_KEY_D:
				m_spring1->SetMotorSpeed(-50);
				break;

			case GLFW_KEY_W:
				replace = true;
				break;
		}
	}

	static Test* Create()
	{
		return new Tiles;
	}
};
```

Thank you very much,
Luis

**Comment by erincatto** [comment]
Hi Luis,

When a fixture is destroyed anything touching that fixture will be woken up. That way if you have a stack of boxes and destroy the bottom box, the stack will fall.

In your case you know you are replacing the ramp so you can force the car to remain asleep.

I hope that helps.
Erin

**Comment by luisgrimaldo** [comment]
Hi Erin,

Thanks for your response.
But if I don't know whether the (ramp) fixture has changed or not.
I tried implementing the following:

1. Keeping tracking of the old fixture's contacts
2. Replacing the fixture with the modified version of it.
3. Running world.step with 0 step time, to find the new contacts attached to the new fixture.
4. Cross reference these new contacts with the old ones and keep the bodies that used to have contacts with the old fixture and still have contacts with the new fixtures asleep.

Only problem is that with this solution, I could potentially have a car floating in the air because the part right below the car was removed (the fixture of the ramp changed) but the car happens to be colliding with let's say another part of ramp fixture, so in step 4, the program still believes the body should be asleep (and floating in the air).

Another solution I thought of is instead of what I do in step 4, I make sure that all the normals of the contacts found in step 1 persist exactly the same as the normals of the contacts with the new fixture, if all the normals persist, then I can set the car to sleep. Do you think that this could cover all the cases and/or if this is the appropriate thing to do?

One more final question, coming back to your response, I understand that anything that was touching a fixture that was removed should be woken up. However, after those bodies are woken why do they need to move if (in this case) there should be no movement, as the configuration/contacts have not changed?

Thanks,
Luis.

**Comment by erincatto** [comment]
Hi Luis,

The car moves a small amount due to warm starting. You should notice the effect diminish with a higher number of velocity and/or position iterations.

The solution to this depends on the needs of your application and how and why the fixtures are being replaced.

Erin

**Comment by luisgrimaldo** [comment]
I see, I guess this falls under a "non-rigid" system. Makes sense.
I figured out a simpler solution that just involved placing a sensor in the "changed" area, then putting every contacted body to sleep and then removing the sensor (which wakes up the bodies that are in contact with the sensor, if any).

Thanks for your prompt responses!
