### ISSUE TITLE
b2DynamicTree::RemoveLeaf - guard against null sibling node

### ISSUE THREAD

**Issue by rmsmith** [erincatto/Box2D#465]
I received a crash report in the wild for a segfault on line 347 of b2DynamicTree:

`m_nodes[sibling].parent = grandParent;`

I suspect that `sibling` was `b2_nullNode` (-1) and therefore the array index operation went out of bounds.  Is it reasonable for the `sibling` to ever be a null node here?  Unfortunately I don't have other context as to the state of the tree when this happened.  I've added a guard against this and have not observed any problems since:

```
if (sibling != b2_nullNode)
{
  m_nodes[sibling].parent = grandParent;
}
```

I also added similar logic on line 368 just in case.

thanks!

**Comment by rmsmith** [comment]
I'm going to close this issue since I don't have the full context of the crash, and it may just have been a side effect of another issue.

**Comment by louis-langholtz** [comment]
Thanks for alerting people to this crash. I'll be keeping my eyes open more for this possibility now!

Incidentally, I'm not confident that the guard code you've provided would make things any better though. While I believe that it'd avoid a crash where you'd seen, I suspect it might just be posting the crash for later in code execution. If `sibling` was -1, then either `m_nodes[parent].child1` or m_nodes[parent].child2` was -1. I don't believe that either of those should be -1 at that point in the `RemoveLeaf` method however but if either are, then something farther upstream seemingly went awry.
