### ISSUE TITLE
detection of persistent contact points not implemented

### ISSUE THREAD

**Issue by mentisn4b** [erincatto/box2d#472]
Detection of persistent contact points occurs in b2GetPointStates() in b2Collision.cpp. It is based on comparing the ``key`` field of a b2ContactID. However, ``key`` is only ever set to 0 (e.g. in b2CollideEdge.cpp, b2CollideCircle.cpp). So detection of persistent contacts is apparently not implemented.

**Comment by erincatto** [comment]
key is in a union with cf and cf is modified in various places
