### ISSUE TITLE
Naming of inline b2Vec2 b2Mul22(const b2Mat33& A, const b2Vec2& v) [b2Math.h]

### ISSUE THREAD

**Issue by netgusto** [erincatto/Box2D#473]
Here:

https://github.com/erincatto/Box2D/blob/master/Box2D/Box2D/Common/b2Math.h#L539

Shouldn't the function be named `b2Mul33` instead ? It's operating on `b2Mat33`, not `b2Mat22`.

**Comment by erincatto** [comment]
The function is using the upper 2 by 2 of the 3 by 3 matrix.
