### ISSUE TITLE
Cannot open Box2D.h [Closed]

### ISSUE THREAD

**Issue by marcphilippebeaujean-abertay** [erincatto/Box2D#480]
I tried everything that I could think of. I created a VS 2015 hello world project. Inside the Box2D folder, I ran premake5 for VS 2015 and built the solution. Copy pasted the library and the include files, then hooked them up with my project. When I include Box2D.h, it's members are recognised by Visual Studio. I even changed my target device to x64. However when I run it, it gives me the error "Cannot open Box2D.h". I would be really happy if someone could help me out with this! Thank you in advance.

**Comment by marcphilippebeaujean-abertay** [comment]
I ended up finding out what the problem was - I had built the Box2D library with sdk version 8.1 - this was not the same version that I had used to build my project. Hope this helps people with the same issue!

**Comment by eXpl0it3r** [comment]
Maybe close this issue since it's fixed/was never a real issue?
