### ISSUE TITLE
Problems to run Testbed example

### ISSUE THREAD

**Issue by 5ruberuto** [erincatto/Box2D#482]
I want to run Testbed example but the program throw this error:

/Testbed 
OpenGL 3.0 Mesa 17.0.7, GLSL 1.30
Error compiling shader of type 35633!
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
Error compiling shader of type 35632!
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
Testbed: ../../Testbed/Framework/DebugDraw.cpp:176: GLuint sCreateShaderProgram(const char*, const char*): Assertion `vsId != 0 && fsId != 0' failed.
Abortado

Any suggestion?

**Comment by erincatto** [comment]
The testbed uses OpenGL 3.3 which does not appear to be supported on the OS you are using. Perhaps you can upgrade your OS. OpenGL 3.3 was released 8 years ago.
