### ISSUE TITLE
Position of my *b2Body is always -107374176.00, meaning it is uninitialized, what am i doing wrong?

### ISSUE THREAD

**Issue by Tim4135** [erincatto/Box2D#488]
Hi,

So whenever I do body->GetPosition the position(x and y) are always -107374176.00.
This means according to the internet, that the variable is uninitialized.
This is my code:
Placed in a class:

```
void Setup(int Type, float X, float Y, float W, float H)//Setups the physics and location of the object, 0 = static(NO COLLISION!), 1 = physics, 2 = physics-static
	{
		type = Type;
		if (1)
		{
			b2BodyDef bodyDef;
			bodyDef.type = b2_staticBody;
			bodyDef.position.Set(0.0f, 4.0f);
			body = world.CreateBody(&bodyDef);

			// Define another box shape for our dynamic body.
			b2PolygonShape dynamicBox;
			dynamicBox.SetAsBox(1.0f, 1.0f);

			// Define the dynamic body fixture.
			b2FixtureDef fixtureDef;
			fixtureDef.shape = &dynamicBox;

			// Set the box density to be non-zero, so it will be dynamic.
			fixtureDef.density = 1.0f;

			// Override the default friction.
			fixtureDef.friction = 0.3f;

			// Add the shape to the body.
			body->CreateFixture(&fixtureDef);

		}
	}
	b2Vec2 GetPosition()
	{
		return body->GetPosition();
	}//till here is in my class

b2Body *body;

b2World world(b2Vec2(0.0, 9.81));


void InitBox2DWorld()
{

}

void UpdateBox2DWorld()
{
	world.Step(1.0 / 5.0, 6, 2);
}
```

//////////////////////////////I call these functions in this order:------------------------------------------

```
InitBox2DWorld();//is empty, I know ;)
ObjectClass object;
object.Setup(0,0,0,10,10);
while(1){
updateBox2DWorld();
b2Vec2 Pos = ocject.GetPosition();
std::cout << Pos.x << ", " << Pos.y; << std::endl;
}
```

does somebody know where my error is, I really don't know what i did wrong?
The HelloWorld example runs fine by the way.

Thanks

**Comment by 1aam2am1** [comment]
Try calling Step over the world.

**Comment by Tim4135** [comment]
Sorry, my mistake, i alreaddy call stepp in the loop, forgot to put it in the post.
Do yoo know what else could be wrong?

**Comment by elemel** [comment]
Not sure that it's a good idea to have your world as a statically allocated object. Try creating it with new once the application has started instead?

**Comment by Tim4135** [comment]
@elemel Wioll try it out now, thanks

**Comment by Tim4135** [comment]
You mean like this right?
b2World *world;
int main()
{
    world = new b2World(b2Vec2(0,9.81));
}

**Comment by Tim4135** [comment]
Fixed it, had some stupid error in my code.
