### ISSUE TITLE
How to render an object with render scaling? Thus simulating objects smaller, and rendering them thus bigger?

### ISSUE THREAD

**Issue by Tim4135** [erincatto/Box2D#489]
Hi,

So I just got Box2D working, now I have another problem:
Currently, I simulate a object by supplying it with pixel sizes, so:
Image of 64x64 gets drawn, and the size in Box2D will also be set a 64x64(Meters).
This renders fine by getting the position and applying it, but now i want to have a 4x4meter object, render as an 64x64 sprite on the screen.
The problem is, that I don't know how I would scale it properly.
Can someone explain me how I would properly set the positions of the sprite accordingly to the b2Body positions?
The only options my graphics renderer provide are these:
```
SetPosition(x,y);
SetScale(x,y);
SetAngle(A);
```
So no vertex modifying and such(may it be nescesery).
Can someone teach me how I would probably convert the sizes to achieve what I want?

Thanks!

**Comment by RedKugelblitz** [comment]
This is the physics engine, not the graphics one mate. Ask for help on the
right place!

**Comment by Tim4135** [comment]
I know this is the physics engine, thats why I ask here how to convert units to correctly display.
The people at opengl forums probably don't know about this engine, and its units.

So thats why I ask here.

Does somebody know this?

**Comment by 1aam2am1** [comment]
Set constant variable that will be your scalar.
And you must multiply any physical size by it.
In sfml you must multiply.

`sf::Sprite s(texutre);
s.setPosition(body->getPosition()*M2P;`

And in box2d you must create smaller body.
You must divide the size of sprite.

**Comment by HughPH** [comment]
Well 64 pixels divided by 4 metres is 16. So if you multiply your metres by
16 then you will get the scale you're looking for - i.e. 64 pixels for a 4
metre object (16:1 as it happens)

If you're struggling with this, though, you might consider something higher
level that will do more of the complicated bits for you - e.g. Unity.

**Comment by Tim4135** [comment]
Then they appear on a comleteley different position.
The reason I want to do this si to learn how to do it, I can use unity and
UNreal engien and such, but that is not what I want.

**Comment by Tim4135** [comment]
@1aam2am1 Thanks, but could you explain a bit more?
If i just multiple, it appears on  a different location, and collision is half the area.

**Comment by HughPH** [comment]
Sounds like you're scaling the size of the object but not the position.

On 16 Mar 2018 11:03, "Tim" <notifications@github.com> wrote:

@1aam2am1 <https://github.com/1aam2am1> Thanks, but could you explain a bit
more?
If i just multiple, it appears on a different location, and collision is
half the area.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/erincatto/Box2D/issues/489#issuecomment-373680549>, or mute
the thread

**Comment by Tim4135** [comment]
What am I doing wrong then?
I do this:
```
Object.CreatePhysicsBox(W/2,H/2); //Custom wrapper for Box2D, arguments passed to box.SetAsBox(WidthParam/2, WidthParam/2);
sprite.SetPosition(Object.body->GetPosition().x*2, Object.body->GetPosition().y*2);//Collision is still smaller then drawn box, and it renders not on the original location.
//replacing the 2 '*' in by /'s also doesn't behave correct
```

How to correctly get the behaivour I want?

**Comment by Tim4135** [comment]
Could someone maybe explain me what calculations to do and why, and explain it from the ground up?(To see if I am doing something wrong, so an explaination from creating the box bodydef, to rendering?)

THanks!

**Comment by abakobo** [comment]
You should post the question on a help forum (please)
This place is for helping the box2d creator to improve it!
http://www.box2d.org/forum/index.php

To have the correct sprite size you have to calculate it yourself depending on the sprite size and the physics scale. Some people use the number of pixel for 1meter in physics, some other the fraction of meter for 1 pixel. But that's the ratio you're looking for. Then you have to know your image size to make it fit with the physics object (just use one dimension for that, height for example).

**Comment by Tim4135** [comment]
@abakobo COuld you explain me how I would do that?

And I will register on the forum and post there as soon as i get the time.

**Comment by louis-langholtz** [comment]
@Tim4135 Another place you may find insight from is the Box2D section of [StackOverflow](https://stackoverflow.com/questions/tagged/box2d) (or in the similar section in [GameDev](https://gamedev.stackexchange.com/questions/tagged/box2d)). You may also want to read up on [linear transformations](https://en.wikipedia.org/wiki/Linear_map) or [transformation matrices](https://en.wikipedia.org/wiki/Transformation_matrix).

**Comment by 1aam2am1** [comment]
If your sprite is on 'bad position'. Think. Have you scaled all objects. Or only this one?
If all then if size of sprite is good to the scale and object in physics, then everything should be okey.

PS. Try seting scale to 1. And changing it in the runtime. Watch what is changing and what not. Scale should make the whole scene bigger. And if sprite are the same the whole time(size). Then there should appear gaps between sprites.

**Comment by erincatto** [comment]
Conversation ended a few months ago
