### ISSUE TITLE
b2WheelJoint random glitch when frequencyHz = 0;

### ISSUE THREAD

**Issue by KAMIKAZEUA** [erincatto/box2d#491]
Using latest code from `master`.

In my game I have simple structure of 2 bodies: 
 - `jointBody` is a simple static square 
 -  `body` is dynamic polygon object. 
All other game simulation with much more complex things goes super stable and I never had any problems with Box2D at about ~6 months already of coding my game. So, I'm assuming that my code is stable.

But now, when I'm trying to create a simple joint with this code:

```
b2WheelJointDef wheelJointDef;
wheelJointDef.Initialize(jointBody, body, body->GetPosition(), b2Vec2(-0.999549448, 0.030014623));
wheelJointDef.collideConnected = false;
wheelJointDef.frequencyHz = 0;
jointWheel = (b2WheelJoint*)world->CreateJoint(&wheelJointDef);
```

I got random glitch, but reproduced very often: game freezes, 100% processor loads and bodies teleported somewhere.. just gone from the screen.
Changing `frequencyHz` to something like 0.01 seems like fixing this(still testing), but it's clearly described:
`"/// Suspension frequency, zero indicates no suspension"`  and it's exactly for me - I need `b2WheelJoint` without suspension. 

So this is some bug with `frequencyHz = 0` value.

**Comment by erincatto** [comment]
The wheel joint has changed for other reasons since this issue was reported. There is non longer frequencyHz. Instead there is a stiffness value. I tried setting this value to zero in the test in wheel_joint.cpp and it remained stable.
