### ISSUE TITLE
Moving objects in paused word, and still have joints work?

### ISSUE THREAD

**Issue by Tim4135** [erincatto/Box2D#492]
Hi,
So I want to create some editor for my game, even though it is going well, I want to be able to stop the simulation, and be able to spawn and move objects.
The problem is, how do I move an object when the game is paused?(But have it like there still are physics, so the cube rotates when grabbed in a corner, and is dragged?)
And how can I then move an object, but have another object that is is jointed to it, move with it?

I maybe know one way to do this, by never pausing the physics, but disabling gravity and have vedy high air resistance.
But I hope there are other ways too.

Thanks!
Btw. I pause the physics by just not calling the step world function.

**Comment by HughPH** [comment]
You can't have physics and not step the world. Stepping is what makes physics calculations happen.

What you could do, though, is clear all the velocities from the objects and set the gravity to 0. Then everything will effectively freeze in place. That does mean you would lose any velocities inbetween pausing and unpausing - so anything falling before you pause will no longer be pausing afterwards. That could be solvable by recording the velocities (angular and linear) before setting gravity to 0 and restoring them before returning gravity to normal... Whether those are accessible depends on the exact implementation you're using.

**Comment by Tim4135** [comment]
@HughPH Thanks for your reply, but if I do like you say, can I still move them, because if i keep setting their speed to 0 every frame, they can't move.(Can they?)
I am using Box2D with c++, what do you mean with implementation?

**Comment by HughPH** [comment]
You're using a C++ implementation of Box2D, there are implementations in other languages - e.g. JavaScript, C# (in fact there are several in C#)

It sounds like you're checking if your pause flag is set for each frame, and only calling Step if it's not paused?

You need a rethink. For a start, you need to keep stepping so your per-cycle check is redundant. Just take it out.

Instead, hold a global "isPaused" variable. Have a "SetPauseState" method.

In pseudocode:

void SetPauseState(bool state){
  if (isPaused == state) return;
  if (state == true){
    // save all linear velocities in a global variable
    // save all rotational velocities in a global variable
    // set gravity to 0
    isPaused = true;
  }
  else
  {
    // restore all linear velocities
    // restore all rotational velocities
    // change gravity back to normal
    isPaused = false;
  }
}

I don't imagine you're using threading, so this should be fine...

**Comment by erincatto** [comment]
Thanks @HughPH I think you addressed this issue well.
