### ISSUE TITLE
Wrong include paths

### ISSUE THREAD

**Issue by jiri** [erincatto/Box2D#504]
Hi,

while trying to build Box2D with CMake, I noticed that the include paths in [Box2D.h](../blob/master/Box2D/Box2D/Box2D.h) all have a `Box2D` folder in the path, whereas there is no Box2D folder next to the file. Removing that prefix fixes the build.

Is this intentional? It doesn't seem right.

**Comment by erincatto** [comment]
Sorry, CMake is no longer supported. Please use Premake5.

**Comment by jiri** [comment]
As I'm sure you're aware from the description, this is not a CMake issue but rather a semantic issues. The file `Box2D.h` is trying to include a *relative* path that does not exist in the source tree.

If it exists after running premake5, it still violates the behaviour of relative include paths.

Please don't close issues before they're resolved.

**Comment by erincatto** [comment]
Here is the premake snippet that builds the Box2D library:

project 'Box2D'
	kind 'StaticLib'
	language 'C++'
	cppdialect 'C++11'
	files { 'Box2D/**.h', 'Box2D/**.cpp' }
	includedirs { '.' }   <<<<<<<<<<<<<<< this sets the include path

In my opinion, this does resolve the issue. However, I will reopen the issue so you can confirm that premake works.

**Comment by jiri** [comment]
Sorry for the delay.

I played around with Premake5 and it does work correctly, it's just a bit jarring how it changes the path semantics. Feel free to close this issue :)

**Comment by erincatto** [comment]
Glad you got it working.
