### ISSUE TITLE
Undeclared identifier `isfinite` when compiling with GCC 5.4 stdlib

### ISSUE THREAD

**Issue by chrahunt** [erincatto/box2d#509]
Test script

```sh
#!/bin/sh
if [ ! -d Box2D ]; then
    git clone https://github.com/erincatto/Box2D.git
fi
cat <<EOF > main.cpp
#include <math.h>
#include <cmath>
#include "Box2D/Box2D/Box2D.h"

int main(int argc, char** argv) {}
EOF
g++ --version
g++ -std=c++11 -IBox2D main.cpp
```

Test output

```
$ ./test.sh
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

In file included from Box2D/Box2D/Common/b2Draw.h:22:0,
                 from Box2D/Box2D/Box2D.h:35,
                 from main.cpp:3:
Box2D/Box2D/Common/b2Math.h: In function ‘bool b2IsValid(float32)’:
Box2D/Box2D/Common/b2Math.h:28:19: error: ‘isfinite’ was not declared in this scope
  return isfinite(x);
                   ^
Box2D/Box2D/Common/b2Math.h:28:19: note: suggested alternative:
In file included from main.cpp:2:0:
/usr/include/c++/5/cmath:601:5: note:   ‘std::isfinite’
     isfinite(_Tp __x)
     ^
```

Under GCC 5.4 `cmath` in the gcc standard library `undef`s `isfinite` but does not provide the corresponding global function. You can see additional discussion on a similar issue in swig/swig#615.

[Godbolt](https://godbolt.org/g/56kAjw) for quick reference showing compilation failure on GCC 5.4 but not other compilers/platforms. The important part is actually the stdlib in use as opposed to the compiler, as I discovered this while using clang with the stdlib on my platform (Ubuntu 16.04.3).

**Comment by erincatto** [comment]
Do you have a fix? I'm not running Linux.

**Comment by mightymos** [comment]
I also had a similar compilation failure/error message, but was able to fix by replacing the offending line in "b2Math.h" with:
return std::isfinite(x);

Compiler version is [g++ (tdm-1) 5.1.0] on Windows 7 64-bit.
This example prompted the fix:
https://en.cppreference.com/w/cpp/numeric/math/isfinite

**Comment by mightymos** [comment]
This compiles and links with the changes to "b2Math.h":
#ifndef B2_MATH_H
#define B2_MATH_H

#include "Box2D/Common/b2Settings.h"
//#include <math.h>
#include <cmath>

/// This function is used to ensure that a floating point number is not a NaN or infinity.
inline bool b2IsValid(float32 x)
{
	return std::isfinite(x);
}

..............

**Comment by jrmclaugh** [comment]
Also occurs while cross compiling for ARM using:
gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04)

The above workaround from mightymos allows it to compile and run successfully.

**Comment by erincatto** [comment]
Currently building fine on Linux via travis-ci.
