### ISSUE TITLE
Add gear joints to "goodbye" destruction dependency tree

### ISSUE THREAD

**Issue by Troid92** [erincatto/box2d#512]
When bodies are destroyed, all their fixtures and joints are implicitly destroyed. You can get a notification of this using `b2DestructionListener` as described in the manual:

> You can implement a b2DestructionListener that allows b2World to inform you when a shape or joint is implicitly destroyed because an associated body was destroyed. This will help prevent your code from accessing orphaned pointers.

This is a wonderful feature. Just write a `SayGoodbye(b2Joint* joint)` function to handle your game's response to a joint disappearing, and you're good to go.
...except for gear joints.

> **Caution**
> Always delete gear joints before the revolute/prismatic joints on the gears. Otherwise your code will crash in a bad way due to the orphaned joint pointers in the gear joint. You should also delete the gear joint before you delete any of the bodies involved.

I am wondering if there is any compelling reason why the gear joint does not get implicitly destroyed when one of its dependencies (the two joints) are destroyed, like everything else in Box2D. It seems incorrect that `b2DestructionListener` does not actually fulfill its promise for all joints.

**Comment by erincatto** [comment]
Won't fix.

The gear joint involves four bodies instead of the normal two bodies, so getting the same behavior would require a lot of extra code and special casing. Not worth it for just one joint type that is also not as commonly used. If I add more joints that attach more than two bodies then it might be worthwhile.
