### ISSUE TITLE
Should this be false?

### ISSUE THREAD

**Issue by hardcoremore** [erincatto/Box2D#518]
https://github.com/erincatto/Box2D/blob/11cda0f41719e85728d6c076b8ff11136cc18934/Box2D/Collision/b2BroadPhase.cpp#L101

Should this be false. This function never returns false, is that normal?

**Comment by 1aam2am1** [comment]
Yes it is normal if that function returns false that means that callback have failed and b2DynamicTree::Query function will return. Not making everything it should.

**Comment by ThrashAbaddon** [comment]
@hardcoremore Are you satisfied with the answer? Maybe the authors can close this one.

**Comment by hardcoremore** [comment]
Yes you can close this one.
