### ISSUE TITLE
Default density should be non-zero

### ISSUE THREAD

**Issue by Troid92** [erincatto/box2d#520]
Right now `b2FixtureDef` sets the density to `0.0f` in its constructor. Static and kinematic bodies ignore density, so this only applies to dynamic bodies. If you forget to set the density on all of a dynamic body's fixtures, "you will get strange behavior" (Box2D Manual Section 2.3). This scenario can happen easily with beginners and can be difficult to identify.

If the default density was something like `1.0f`, forgetting to set the density means the object is heavier or lighter than expected, which is much easier to diagnose upon viewing the scene as Box2D continues to function normally. As far as I can tell there are no disadvantages to this change other than backwards compatibility.

**Comment by erincatto** [comment]
Addressed in #591
