### ISSUE TITLE
b2CircleShape::RayCast doesn't cover all edge cases.

### ISSUE THREAD

**Issue by outermeasure** [erincatto/box2d#523]
Failing test:

```
b2CircleShape cs;
cs.m_radius = 1;
cs.m_p.x = 0;
cs.m_p.y = 0;
b2RayCastInput ray;

ray.maxFraction = 1;

ray.p1.x = 0;
ray.p1.y = 0.5;

ray.p2.x = 0;
ray.p2.y = 1.5;

b2RayCastOutput out;

b2Transform identity;
identity.SetIdentity();

printf("Ray cast result %d\n", (int)cs.RayCast(&out, ray, identity, -1));
```

The ray intersects the circle in (0, 1) but RayCast returns false instead. The error seems to originate from the fact that both solutions of a 2nd degree equation are not considered.

```
// Find the point of intersection of the line with the circle.
float32 a = -(c + b2Sqrt(sigma));
```

**Comment by erincatto** [comment]
Yeah, rays that start inside a convex shape do not collide. I could support this for circles and polygons, but then the algorithms become more expensive and complex. Further, we often don't want this behavior, so then the API needs to be more complex. Perhaps you just want to know if the ray starts inside but don't need the collision to actually happen. And so on. Then I would need to handle all these cases and test them all. So about twice as much code to handle an uncommon use case.

**Comment by aslepov78** [comment]
The b2CircleShape :: RayCast method should work correctly on its own. It doesn't matter how you use it in your code.

**Comment by erincatto** [comment]
A function is correct if it does what it is designed to do. I have designed all the ray cast functions to not collide internally. In my experience, internal collisions are not needed or wanted most of the time. For example, suppose my character is represented by a circle. If I want to fire rays out from the center of the character to shoot a weapon or launch a grapple, I don't want that ray to be stopped by my own character collision.

On the other hand I should document this behavior. I may also offer an additional RayCastDoubleSided function for circles.

**Comment by aslepov78** [comment]
Oh. The function does exactly what the signature says. And if for this you need long comments then this is a bad function

**Comment by erincatto** [comment]
Circles in Box2D are solid.

Locking this issue due to unproductive conversation.
