### ISSUE TITLE
Data race in b2BlockAllocator first-time initialization

### ISSUE THREAD

**Issue by tlemo** [erincatto/box2d#527]
The one-time initialization check (using b2BlockAllocator::s_blockSizeLookupInitialized) introduces a [data race](https://github.com/erincatto/Box2D/blob/a174dbac1bc32e05e790cd867d9e30fb37681d47/Box2D/Common/b2BlockAllocator.cpp#L66).

The fact that Box2D API is not thread-safe is mentioned in the [FAQ](https://github.com/erincatto/Box2D/wiki/FAQ#is-box2d-thread-safe), although it doesn't have to be thread-hostile. In particular, one can easily assume that using separate (not shared) instances of b2World on different threads works since everything is allocated from the b2World.

Fortunatelly, this small issue can be easily fixed (for example C++11 std::call_once or static local initialization would avoid the race)

For additional context, here's the related thread on the Box2D forum: https://box2d.org/forum/viewtopic.php?f=3&t=10334

**Comment by erincatto** [comment]
Fixed in #583
