### ISSUE TITLE
Strange behaviour with Pulley Joints

### ISSUE THREAD

**Issue by dibyendu** [erincatto/box2d#530]
I've written a small demo with pulley joints: https://jsbin.com/kaderol/edit?html,output

The pulley system on the right is behaving normally, while the one on the left is acting strange.

Can someone explain why the lighter mass attached to the left string of the left pulley system suddenly stopped during its ascend ? I was expecting it to reach the top point where it is attached to the ground.

**Comment by erincatto** [comment]
Pulleys get unstable if the length on one side gets too small. The pulley constraint deactivates if one side gets shorter than 5 centimeters.

This is why the example in the testbed has collision to stop the length from becoming too short.
