### ISSUE TITLE
Destructive Terrain

### ISSUE THREAD

**Issue by asvsfs** [erincatto/box2d#531]
Would be a very cool feature to have inside box2d! if implemented efficient enough.

**Comment by HughPH** [comment]
There's a demo somewhere of Box2D objects being "cut up" based on angle of
impact and velocity. It's not a difficult problem to solve, but it's an
implementation detail that would apply to any convex hull, if so
configured. The biggest issue you have is controlling the number of pieces
that get created and will be created. (Turning a concave hull into convex
hulls has been solved, a and also contributes more objects to the world).
Unless you want the user to interact with the destroyed scenery, or for the
pieces of scenery to hit or bounce off objects accurately, it might be
better to destroy the entire object and implement the falling pieces in a
separate particle engine.

I would say it's out of scope of the aims of Box2D, but I'm happy to be
proven wrong.

**Comment by erincatto** [comment]
Yes, this is currently not in my plans. It should be possible to achieve a lot of this with the existing features of Box2D.
