### ISSUE TITLE
Q: How do you know the measurement of a meter?

### ISSUE THREAD

**Issue by DimitarBogdanov** [erincatto/box2d#533]
**This is a question.**

So, I was looking at [the FAQ page](https://github.com/erincatto/Box2D/wiki/FAQ) and I saw this on the bottom:
![image](https://user-images.githubusercontent.com/27803292/52745277-4c908000-2fe7-11e9-8ce5-efed12d54af2.png)
How do you know how much a metre is? Everything on a computer screen is displayed using pixels - so how exactly do you know how much a metre is?

**Comment by abakobo** [comment]
Just chose a pixel/meter ration and multiply your world b2vec coordinates
to get the screen coordinates.
Give dimensions in meter to the objects as in real life.
