### ISSUE TITLE
Feature Request: Add a function to trace a shape in box2d

### ISSUE THREAD

**Issue by roig** [erincatto/box2d#534]
Hello!

I think it would be very useful to have a function to trace a shape between a point A to a point B (and rotation) and get the collisions/overlaps etc... from that trace. Like a RayCast but with a shape! :+1: 

Something like this would be awesome:
[convexSweepTest](http://docs.ros.org/diamondback/api/bullet/html/classbtCollisionWorld.html#aeeee096b94a5eb31e8c88a29b6c69d37)

Thank you!

**Comment by TylerGlaiel** [comment]
+1, unity has [CircleCast](https://docs.unity3d.com/ScriptReference/Physics2D.CircleCast.html), [BoxCast](https://docs.unity3d.com/ScriptReference/Physics2D.BoxCast.html), and [CapsuleCast](https://docs.unity3d.com/ScriptReference/Physics2D.CapsuleCast.html), all very useful functionality and was surprised to find those missing from box2D itself

**Comment by erincatto** [comment]
Yeah, the low level routines exist to support this. Completing this feature requires:
- Implement swept AABB in dynamic tree
- Create API in b2World

**Comment by roig** [comment]
Any chance to see this in v3.0, please? 🙏

**Comment by gabrieldevsouza** [comment]
Is there any work on this?

**Comment by erincatto** [comment]
I'm planning to have this in v3.0. No more features for v2.4.
