### ISSUE TITLE
The latest version isn't easy to build

### ISSUE THREAD

**Issue by yurivict** [erincatto/box2d#535]
I tried revision ef96a4f on FreeBSD, followed instructions, and got failures:
```
$ lua52 premake5.lua gmake
lua52: premake5.lua:4: attempt to call global 'workspace' (a nil value)
stack traceback:
	premake5.lua:4: in main chunk
	[C]: in ?
[yuri@yv /usr/ports/misc/box2d/work/Box2D-ef96a4f]$ lua53 premake5.lua gmake
lua53: premake5.lua:4: attempt to call a nil value (global 'workspace')
stack traceback:
	premake5.lua:4: in main chunk
	[C]: in ?
```
Not sure where to go from here.

I discovered that cmake-based build is nicer.

**Comment by mechazod** [comment]
@yurivict I works fine on `premake5 xcode`. I downloaded premake v5 on https://premake.github.io/download.html#v5. 

Then comment the line `// IM_ASSERT(0); // Could not load file.`

**Comment by monalisir** [comment]
@mechazod I have compiled it with premake v5. you need to copy the Data/DroidSans.ttf to the folder which the binary files in. 

My problem is 
2019-02-21 17:21:20.497475+0800 Testbed[34248:533683] *** Assertion failure in -[GLFWContentView _createLayerAndInitialize], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.10.106/AppKit.subproj/NSView.m:17237

I can not found how to resolve this issue.

any idea?

**Comment by mechazod** [comment]
@monalisir No, idea to resolve. I'm beginner on this. But what can I suggest is go pull the latest master and try to create a new `Build` using premake5 that I suggest. 

<img width="918" alt="screen shot 2019-02-22 at 2 20 00 pm" src="https://user-images.githubusercontent.com/16739905/53223638-fb4e5380-36ac-11e9-9e3a-5b7639bfe69e.png">

**Comment by monalisir** [comment]
yes, premake5, master branch, latest code. But still failed. 
could u can launch the Testbed binary?

**Comment by mechazod** [comment]
Yes, it works fine when i run exactly the compile.
<img width="1122" alt="screen shot 2019-02-22 at 4 58 40 pm" src="https://user-images.githubusercontent.com/16739905/53231126-2c398300-36c3-11e9-9287-d646b93cc1f3.png">

**Comment by jonatasschagas** [comment]
I had the same issue and managed to solve it by: 
1. Installing the latest version of GLFW and GLEW. I've followed this tutorial here: https://riptutorial.com/opengl/example/21105/setup-modern-opengl-4-1-on-macos--xcode--glfw-and-glew-
2. Opening the Testbed project in Xcode.
2. Then dragging the libGLEW.2.1.0.dylib and libglfw.3.3.dylib files (from /usr/local/lib)  to the folder "Frameworks" in Xcode.
3. Then deleting the folder "glfw" from the project.

I think the version of GLFW present in Testbed is incompatible with Mojave. I hope that helps :)

**Comment by yurivict** [comment]
It should be easy to build in a sense that the user should type one command - and it should build it.

Otherwise, are you suggesting that every user should perform multiple steps to install just one package? There is about a thousand of packages that the average user needs to have installed.

**Comment by jonatasschagas** [comment]
Sorry, I've missed the point from the thread. I just pointed out one possible solution to get this working in OSX Mojave. I agree with you that it should be easier to get it up and running. Solving this issue might be trivial for someone who has experience in c++ development env. on Mac but for beginners like me it might take a while to figure out how to get it working... Maybe someone who is knowledgeable about this could update the libs in order to make them compatible with more recent Mac OSX versions?

**Comment by erincatto** [comment]
Should be easier now with the cmake build system. There are some specific instructions for XCode here https://github.com/erincatto/box2d/blob/master/README.md
