### ISSUE TITLE
Feature Request: Testbed OpenGL 2.1 compatibility

### ISSUE THREAD

**Issue by orhaneee** [erincatto/box2d#538]
Hi,

I am building in Raspberry Pi 3 and as you know, it supports OpenGL 2.1 at most.

So, do you have any idea to make current Testbed compatible to GL 2.1?

**Comment by erincatto** [comment]
Sorry, I'm all in on OpenGL 3.0. Support for 2.1 would require somebody to fork and support that feature.

**Comment by 1aam2am1** [comment]
@orhaneee Install mesa3d, a opengl software implementation to support programs with unsuporten opengl version.
