### ISSUE TITLE
How to using Box2D in Android NDK?

### ISSUE THREAD

**Issue by ShaoyuanLi** [erincatto/Box2D#540]
I am developing a 2D game in Android and want to use [Box2D][1] as 2D Collide Engine , However using Box2D would cause a error in NDK cmake build: 

    In file included from ../../../../amazing/amazing_engine/dev/dep/Box2D/include/Box2D/Box2D.h:35:
    In file included from ../../../../amazing/amazing_engine/dev/dep/Box2D/include/Box2D/Common/b2Draw.h:22:
    ../../../../amazing/amazing_engine/dev/dep/Box2D/include/Box2D/Common/b2Math.h:28:9: error: use of undeclared identifier 'isfinite'; did you mean 'std::isfinite'?
            return isfinite(x);
                   ^~~~~~~~
                   std::isfinite

I search it and find some similar situation but they are all in Visual Studio - Windows:

 1. some people say that this is a solved bug of VS STL Library
 2. other people say that this is a situation caused by NDK and could be solved by changing gcc compile options(add -lm) but I use android studio in Mac and build with cmake and clang . I try to add

`add_compile_options("-lm")`

in my CmakeLists.txt which is useless.

How to solve this question?Is it really a bug of NDK?

  [1]: https://github.com/erincatto/Box2D

My OS : MacOS 10.14.4
NDK Version : r16b
Cmake Version : 3.6.4111459

**Comment by 1aam2am1** [comment]
Change return isfinite(x); to
               return std::isfinite(x);

**Comment by ShaoyuanLi** [comment]
> Change return isfinite(x); to
> return std::isfinite(x);

In fact I try to change it and get some similar error as above .Sorry to not mention this in above issue.

**Comment by 1aam2am1** [comment]
Ndk can have some library issues. But if you change code in box2d it should compile.

**Comment by ShaoyuanLi** [comment]
> Ndk can have some library issues. But if you change code in box2d it should compile.

You are right.I use a older NDK and cause some errors.I change 25 functions of std in box2d and error disappear.
it is not bug of Box2D . I would not create MR and hope this issue would help some people like me /(ㄒoㄒ)/~~.
