### ISSUE TITLE
Faster SolveTOI in some cases

### ISSUE THREAD

**Issue by jhoffman0x** [erincatto/box2d#541]
I had an issue where SolveTOI was using 40% of the step even though the majority of contacts were not eligible for TOI (both bodies were dynamic and not bullets, or one of the fixtures was a sensor). I was able to reduce that to 3% by partitioning contacts based on TOI eligibility.

During creation, contacts that include a sensor or two non-bullet dynamic bodies can be considered ineligible for TOI, and inserted into one end of the contact list, while contacts that are eligible for TOI are inserted into the other end. Then in SolveTOI, the loop that finds the minimum contact only needs to iterate over the eligible portion of the contact list.

This adds some cost to functions that modify TOI eligibility: b2Fixture::SetSensor and b2Body::SetBullet must iterate through the body's contacts to check if eligibility changed, and move the contact to the other partition if necessary. Based on normal usage this trade-off should be worth it.

Here are the changes in SolveTOI times for all tests that had times greater than 0.01ms (average from 4 runs).

Tumbler (1800 steps): 0.12ms -> 0.05ms
Add Pair Stress Test (240 steps): 0.48ms -> 0.23ms
Multithread Demo (1800 steps): 5.49ms -> 0.37ms

Multithread Demo is a test from my multithreaded fork, but there's not any multithreading in the test itself. Here's a copy if you want to reproduce with it: https://pastebin.com/DqRCVHq6

If you look at the implementation in my fork you'll see that I used a contact array rather than a list. This just made it easier to assign ranges of contacts to different threads for collision processing.

**Comment by ljluestc** [comment]
```

// During contact creation, partition contacts based on eligibility.
if (IsTOIEligible(contact)) {
    eligibleContacts.push_back(contact);
} else {
    ineligibleContacts.push_back(contact);
}

// During SolveTOI, iterate only over eligibleContacts to find minimum TOI.
for (const auto& contact : eligibleContacts) {
    // Find minimum TOI among eligible contacts.
    // ...
}

// When SetSensor or SetBullet is called, update contact eligibility.
void b2Fixture::SetSensor(bool isSensor) {
    // Check if eligibility changed.
    if (IsTOIEligible(contact)) {
        // Move contact from ineligibleContacts to eligibleContacts.
        // ...
    } else {
        // Move contact from eligibleContacts to ineligibleContacts.
        // ...
    }
}
```
