### ISSUE TITLE
Need help exporting Box2D Testbed Simulation Data

### ISSUE THREAD

**Issue by YipanG1337** [erincatto/box2d#542]
Hi there!

First of all, I'm very new to Box2D. For my first project I've created a test to simulate simple pendulum with moving support to study the relationship between cart velocity along horizontal line and angle of deflection of the rope. The test is successful. However I am having trouble to export the data of velocity over time and the angle of deflection. How can I obtain the aforementioned data so that I could plot a graph with that information? Below is the image for the simulation setup
![Setup](https://user-images.githubusercontent.com/50634639/57719612-b5ed6100-76b2-11e9-9c46-fd8acf48b632.PNG)

**Comment by erincatto** [comment]
Sorry for the late reply. I recommend asking this sort of question here: https://discord.gg/gYX8D9
Basically you want to find where b2Word::Step is called and put some code there to print the body state. You can use function on b2Body to get this.
