### ISSUE TITLE
Proxy Move Displacement

### ISSUE THREAD

**Issue by flyover** [erincatto/box2d#544]
When a body has a larger center of mass offset (b2Body::m_sweep.localCenter), using the transform position sometimes yields a displacement in the wrong direction for moving the broad phase proxy.  The issue is more noticeable when the body has a fast rotation.  See #543 for an exaggerated example.  Using the body sweep center might be a better solution.

**Comment by erincatto** [comment]
Addressed in 0a2e35a0e24271468014ea9f118088c3f75e3363
