### ISSUE TITLE
Shouldn't we only wake bodies up when isTouching is true and not just when their aabb collide?

### ISSUE THREAD

**Issue by luisgrimaldo** [erincatto/box2d#547]
I have a setup where time to sleep is lower and the linear sleep tolerance is higher to bring the simulation to a resting state faster, however, if later a body goes near these asleep bodies (not touching them), they wake up and move for a little until (I'm guessing the new time to sleep for each body), thoughts on that? and how to virtually prevent it. In theory to me it seems like even if i were to increase the time to sleep to a higher number, this will continue to occur.

Should the awake = true only occur when isTouching == true?
https://github.com/erincatto/Box2D/blob/ef96a4f17f1c5527d20993b586b400c2617d6ae1/Box2D/Dynamics/b2ContactManager.cpp#L288-L293

Cheers,
Luis

**Comment by erincatto** [comment]
Good find. This body waking is not needed here at all. It is done elsewhere (and only when touching).
913a40a271d883b9711fd0d39a9df088145a7d26
