### ISSUE TITLE
Use own images for fixtures

### ISSUE THREAD

**Issue by HabButterimAuge** [erincatto/box2d#556]
Hello!

Im new to Box2D and completed the iforce2D tutorial but I have one question. How do I use my own images and not these from the testbed. Is there any possibility to use a png/jpg for fixtures or do I have to use SFML and set the position/angle every timestep again?
I did not find anything about this topic which answered my question!

Thanks!

**Comment by abakobo** [comment]
Box2d does not provide any graphics support. You have to run your own. Typically using glfw or sdl.

**Comment by chapterjason** [comment]
SFML is a nice library to start with.
