### ISSUE TITLE
Bug report: Condition for reaching b2RopeJoint upper limit seems incorrect

### ISSUE THREAD

**Issue by Fakor** [erincatto/box2d#560]
When using the b2RopeJoint I need to know when I have reached its limit. However when making the call `b2RopeJoint::GetLimitState()` I don't receive `b2LimitState::e_atUpperLimit` as I expect.

When doing the following change in `b2RopeJoint::InitVelocityConstraints` I seem to get the behavior that I want:
`float32 C = m_length - m_maxLength;
	if (C > 0.0f)`
to
`float32 C = m_length - m_maxLength;
	if (C >= 0.0f)`

**Comment by erincatto** [comment]
What do you think about an alternative API that just returns the current length and you can determine the state yourself?
I'm migrating joints to use predictive limits and so I will soon no longer need to use the limit state internally.

**Comment by erincatto** [comment]
1025f9a10949b963d6311995910bdd04f72dae6c
