### ISSUE TITLE
[CMake] fix source_group for include

### ISSUE THREAD

**Issue by irov** [erincatto/box2d#564]
please fix src\CMakeLists.txt line 107

'source_group(TREE "../include" PREFIX "include" FILES ${BOX2D_HEADER_FILES})'
to
`source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}/../include" PREFIX "include" FILES ${BOX2D_HEADER_FILES})`

Thanks!

**Comment by Milerius** [comment]
WTF IS THIS full broken

**Comment by erincatto** [comment]
I'll fix this, but I'm curious. What does this break?

**Comment by Milerius** [comment]
../include is relative to your projet root directory, if you use box2d as subdirectory he will look for this directory from the root one leading to error

**Comment by Milerius** [comment]
Use CMake current source dir all the time

**Comment by erincatto** [comment]
Will do. Thanks for the explanation.

**Comment by erincatto** [comment]
https://github.com/erincatto/box2d/pull/566

I found another ../include. Please let me know if my fix looks correct.

**Comment by erincatto** [comment]
Fixed
