### ISSUE TITLE
[Linux]samples crash "Assertion `0' failed". data/DroidSans.ttf folder is missing from samples directory after building

### ISSUE THREAD

**Issue by zalnur** [erincatto/box2d#570]
In samples/main.cpp line 88

`const char* fontPath = "Data/DroidSans.ttf"`, but _data_/DroidSans.ttf (case sensitivity) is found instead in the same directory.
+-box2d
   |--samples
       |---main.cpp
       |---_data/DroidSans.ttf_
       .
       .

After building, build/samples/samples crashes with error "Assertion `0' failed", because data/DroidSans.ttf is missing from build/samples directory 

+-box2d
|--build
|---samples
|----samples
|----_data/DroidSans.ttf <--- missing. samples crashes when not present_

not sure if this issue is present on windows.

**Comment by erincatto** [comment]
Try running the samples from the box2d/samples folder.

**Comment by erincatto** [comment]
Closing. I believe the only problem is the startup folder. At some point I will try to get cmake to copy the font file to the build folder.
