### ISSUE TITLE
How to integrate the latest box2d into xcode, this is too difficult

### ISSUE THREAD

**Issue by zuqiu123** [erincatto/box2d#571]
Hello, how do you integrate this into the latest xcode11.2.1, I didn't find any related teaching, others are too old to integrate, can you tell me or there are other detailed documents, thank you

**Comment by erincatto** [comment]
master is using cmake. You can run build.sh or use cmake directly. Please see the building instructions on the main page.

**Comment by zuqiu123** [comment]
Thanks for your reply, I use MAC, I now run the script `build.sh` and generate the `build` folder

![image](https://user-images.githubusercontent.com/15611129/71790047-61e02400-3069-11ea-9d24-833db713bbc3.png)

Then put the compiled `build folder` into Xcode, but it will report an error `cassert' file not found`

![image](https://user-images.githubusercontent.com/15611129/71790160-e7fc6a80-3069-11ea-933e-90222a3488da.png)

I integrated this for the first time, so I don't know much about it, what I did wrong, or what files I need to import from the build into Xcode. Could you please tell me? I have been searching the data for two days, but there is no relevant information

**Comment by erincatto** [comment]
It looks like you are trying to copy the samples and run that. It will not find the font file and assert. The font file is in samples/data. You can copy that file manually.

**Comment by zuqiu123** [comment]
Sorry, maybe I didn't make it clear enough. At present, I want to integrate` box2d` into `Xcode`, but after I run` build.sh` and generate the `build`folder, I don't know what to do, I don't know `which files` to put into Xcode

**Comment by erincatto** [comment]
build.sh is to build the samples. It also builds the library, but how you hook that into xcode is up to you. If it was me I would just copy over the src and include folders into my project and add the files manually. But this depends on what workflow you like.

**Comment by erincatto** [comment]
I added explicit Xcode steps to the readme:
https://github.com/erincatto/box2d/blob/master/README.md

**Comment by erincatto** [comment]
Resolved
