### ISSUE TITLE
Switch to different file format of manual

### ISSUE THREAD

**Issue by Wuzzy2** [erincatto/box2d#574]
The manual currently is in DOCX format. But I don't have Microsoft Word and I don't want to have it. Is this really the only way to access the documentation?

Can you please switch to a format that is not proprietary?

OpenDocument Format is one option (`.odt`, used by e.g. LibreOffice and OpenOffice.org).
An export to PDF would also be fine.

A HTML manual would be even better.

**Comment by 1vanK** [comment]
https://github.com/erincatto/box2d/blob/ecatto/manual/docs/manual.md

**Comment by erincatto** [comment]
I agree, I'm working on this currently. If you like, you can try building the manual in that branch and send me your feed back. Feel free to comment here: https://github.com/erincatto/box2d/pull/573

**Comment by Wuzzy2** [comment]
Ah thanks. `manual.md` looks good.

**Comment by Wuzzy2** [comment]
However, I find it very hard to navigate. There's no TOC, but that's a different issue …

**Comment by erincatto** [comment]
manual.md is not supposed to be read directly. I put Doxygen build instructions in the pull request notes.

**Comment by erincatto** [comment]
Documentation is now available online in HTML.

https://box2d.org/documentation/
