### ISSUE TITLE
TESTBED not compiling

### ISSUE THREAD

**Issue by 1aam2am1** [erincatto/box2d#590]
In testbed/main.cpp there is missing #include <crtdbg.h> header. Therefore lines:
```
#if defined(_WIN32)
	// Enable memory-leak reports
	_CrtSetDbgFlag(_CRTDBG_LEAK_CHECK_DF | _CrtSetDbgFlag(_CRTDBG_REPORT_FLAG));
#endif
```
are not compiling. _CrtSetDbgFlag is missing.

> testbed\main.cpp:479:17: error: '_CRTDBG_LEAK_CHECK_DF' was not declared in this scope
  _CrtSetDbgFlag(_CRTDBG_LEAK_CHECK_DF | _CrtSetDbgFlag(_CRTDBG_REPORT_FLAG));
                 ^~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.

**Comment by erincatto** [comment]
What compiler are you using?

**Comment by erincatto** [comment]
c1b8c3ba89dcdfc651754e63167489ec922118fb
