### ISSUE TITLE
unit-test complier error on mingw32

### ISSUE THREAD

**Issue by ShireHong** [erincatto/box2d#593]
Make sure these boxes are checked before submitting your issue - thank you!

- [✔] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)
- [ ] Consider providing a dump file using b2World::Dump

I have this problem when i use mingw32 to complier the box2d code:

```
In file included from D:\git_hub\box2d\unit-test\hello_world.cpp:27:0:
D:\git_hub\box2d\unit-test\doctest.h: In function 'void doctest::{anonymous}::color_to_stream(std::ostream&, doctest::Color::Enum)':
D:\git_hub\box2d\unit-test\doctest.h:3757:33: error: 'fileno' was not declared in this scope
            (isatty(fileno(stdout)) == false && getContextOptions()->force_colors == false))
                                 ^
D:\git_hub\box2d\unit-test\doctest.h: At global scope:
D:\git_hub\box2d\unit-test\doctest.h:4634:14: error: 'mutex' in namespace 'std' does not name a type
         std::mutex mutex;
```

**Comment by erincatto** [comment]
Looking for with mingw32.

**Comment by ShireHong** [comment]
I add 
 `add_definitions("-std=gnu++11") 
`in camke list according the advise on stackoverflow,but it can't work

**Comment by 1aam2am1** [comment]
Use mingw64. Mingw32 is not updated anymore and don't have c++11 version supported.

**Comment by ShireHong** [comment]
Thanks @1aam2am1 ,i remove the "c++11" flag in cmake list,it seems ok.
``set_target_properties(unit_test PROPERTIES
	#CXX_STANDARD 11
    CXX_STANDARD_REQUIRED YES
    CXX_EXTENSIONS NO
)

**Comment by 1aam2am1** [comment]
https://en.cppreference.com/w/cpp/thread/mutex
Mutex was implemented in c++11.
Without is you won't compile this program. You should use mingw64.
http://mingw-w64.org/doku.php/download/mingw-builds

**Comment by ShireHong** [comment]
> https://en.cppreference.com/w/cpp/thread/mutex
> Mutex was implemented in c++11.
> Without it you won't compile this program. You should use mingw64.
> http://mingw-w64.org/doku.php/download/mingw-builds

thanks,that's very helpful

**Comment by erincatto** [comment]
Looks like this has been answered. Thanks @1aam2am1
