### ISSUE TITLE
Can't get rotation point to be around (0,0) for objects with multiple fixtures

### ISSUE THREAD

**Issue by ForsakenCreator** [erincatto/box2d#600]
When I add multiple fixtures to a single body using Box2D, the body rotates around the centre point of the first fixture (polygon), instead of the centre point of the body (0,0). Imagine like this: enter image description here

[Example](https://i.stack.imgur.com/zY6Um.png)

The centre point of the shape is (0, 0). How can I make it so that it rotates around the true centre point instead of the centre of the first fixture?

**Comment by elemel** [comment]
Rotation should normally be around the centre of mass. What densities are you setting for the fixtures? Do you have a link to the code? (Or a minimal repro.)

**Comment by ForsakenCreator** [comment]
I'm using AddTorque to rotate the object, I think that also matters in how rotation is handled? The current density set to the fixtures is 1 as default(so is friction and restitution).

```
 public CreateBody(bodyType: BodyTypes, collider: PhysicsColliderComponent, options: PhysicsOptions): Box2DBody {
    //create body def
    let shape = collider.mesh;    
    let position = collider.gameObject.transform.position;

    let bodyDef = new Box2DBodyDef(bodyType, position, options);
    let shapeCount = shape.PointSets.length;
    let box2DShapes = Array<b2Shape>(shapeCount);
    let b2Body = this._b2world.CreateBody(bodyDef.box2DBodyDef);

    for (let i = 0; i < shapeCount; i++) {

      let b2Shape = new b2PolygonShape();
      let polygon: Vector2[];
      polygon = shape.GetScaledPoints(collider.gameObject.transform.scale)[i]; // scales points

      b2Shape.Set(polygon);
      box2DShapes[i] = b2Shape;
    }

    //create box2D fixtures
    for (let i = 0; i < box2DShapes.length; i++) {
      let fixture = new b2FixtureDef();      
      fixture.shape = box2DShapes[i];
      fixture.density = options.densityValues[i];
      fixture.friction = options.frictionValues[i];
      fixture.restitution = options.resitutionValues[i];
      b2Body.CreateFixture(fixture);
    }

    //make Box2DBody
    let body = new Box2DBody(b2Body, new ID().ID, bodyType);

    //add Box2DBody to bodies
    this._bodies.set(body.ID, body);
    body.gameObject = collider.gameObject;

    if (bodyType == BodyTypes.STATIC) this._staticBodies.push(body.ID);
    if (bodyType == BodyTypes.KINEMATIC) this._kinematicBodies.push(body.ID);
    if (bodyType == BodyTypes.DYNAMIC) this._dynamicBodies.push(body.ID);

    return this._bodies.get(body.ID) as Box2DBody;
  }
```

**Comment by elemel** [comment]
That doesn't look like regular Box2D code. What programming language and game engine is this? If this is for a specific game engine, it might be easier to get help in their forums.

Either way, I don't have enough context to understand what's wrong. Can you post a complete repro that is easier for others to inspect and run?

**Comment by 1aam2am1** [comment]
Unity Box2d. Use unity phisics.

**Comment by erincatto** [comment]
Yeah, the body should rotate about the center of mass. Unity might be doing something internally that affects this. If you can reproduce the problem in the Box2D testbed, feel free to re-open.
