### ISSUE TITLE
cmake 32bit  - box2D

### ISSUE THREAD

**Issue by DrBrown777** [erincatto/box2d#602]
I collect the library through cmake I get the 64bit version, how do I generate 32bit box2D.lib?
Maybe there are some flags at build.bat?

please help...!

**Comment by Hexlord** [comment]
Use -A Win32 switch when generating with cmake, see https://stackoverflow.com/questions/28350214/how-to-build-x86-and-or-x64-on-windows-from-command-line-with-cmake .
This issue is not related to Box2D.

**Comment by DrBrown777** [comment]
thanks, I'm just learning.
