### ISSUE TITLE
Contact Create/Destroy Performance (micro-optimisation)

### ISSUE THREAD

**Issue by HughPH** [erincatto/box2d#605]
The Contacts Register can be turned into a one-dimensional array by creating an index with:
FixtureA.ShapeType << 2 + FixtureB.ShapeType
With the current shapes, this creates a continuous index running from 0 to 15.
When expressed as a Switch statement, in C# at least, the compiled code is an incredibly efficient direct array of JMPs:

https://bit.ly/2NxOWt9

Since the Type enum is const, so too can be descriptive names, e.g.
`const int CircleCircle = e_circleShape << 2 + e_circleShape;`

The switch has some duplication, but there are no comparators in the compiled code, so this saves on if statements.

Something like:
```cpp
int shapePair = fixtureA.ShapeType << 2 + fixtureB.ShapeType;
switch (shapePair) {
  case CircleCircle: b2CircleContact.Create(fixtureA, indexA, fixtureB, indexB, blockAllocator);
  ...
  case CirclePolygon: b2PolygonCircleContact.Create(fixtureB, indexB, fixtureA, indexA, blockAllocator);
  ...
  case PolygonCircle: b2PolygonCircleContact.Create(fixtureA, indexA, fixtureB, indexB, blockAllocator);
}
```

I don't think there's much additional maintainability overhead, and the switch statement would be very clear in intent and operation.

**Comment by mtsamis** [comment]
Hey! While this can be an improvement in C# where there are specific instructions and limitations in the VM, I don’t think this is an improvement in C++. A 2d array will compile to similar code without the need to make the array 1d. I think it can even compile to a single indirect jump in the specific case. 

Have you done any c++ specific benchmarks/disassembling?

**Comment by HughPH** [comment]
Thanks for the input! I haven't checked, no. I'm afraid I don't have the tools at hand.

It would be good to see what happens with the current code - I agree the array will essentially be compiled to the same thing, since it's declared `[e_shapeCount][e_shapeCount]`. However, there are some `if` statements to determine the correct parameter order:

```
	b2ContactCreateFcn* createFcn = s_registers[type1][type2].createFcn;
	if (createFcn)
	{
		if (s_registers[type1][type2].primary)
		{
			return createFcn(fixtureA, indexA, fixtureB, indexB, allocator);
		}
		else
		{
			return createFcn(fixtureB, indexB, fixtureA, indexA, allocator);
		}
	}
	else
	{
		return nullptr;
	}
```

They'll only appear once, but they'll be executed on every contact creation. I agree this would be a micro-optimisation (hence the title) and that a better focus for gains would be SolveTOI.

I think an equivalent approach would be to create two Create implementations with swapped inputs, e.g. `CreatePrimary(fixtureA, indexA, fixtureB, indexB, allocator)` and `CreateSecondary(fixtureB, indexB, fixtureA, indexA, allocator)`, so that `s_registers[e_polyShape][e_circleShape]` would call `b2PolygonCircleContact.CreatePrimary` and `s_registers[e_circleShape][e_polyShape]` would call `b2PolygonCircleContact.CreateSecondary`. The first `if` may be unavoidable.

**Comment by mtsamis** [comment]
> It would be good to see what happens with the current code

Here, I did some research on the generated code for fun and here are the results:
the C++ compiled version of the b2Contact::Create function is already quite efficient and there is no need to make the array 1d. Here's the relevant disassembly with comments

```asm
│ mov rax, qword [r10 + 0x18]  ; fixtureA->m_shape
│ mov eax, dword [rax + 8]     ; fixtureA->m_shape->m_type
│ mov rsi, qword [rdx + 0x18]  ; fixtureB->m_shape
│ mov esi, dword [rsi + 8]     ; fixtureB->m_shape->m_type
│ lea rsi, qword [rsi + rsi*2] ; rsi *= 3 (because sizeof(b2ContactCreateFcn) = 3 * 8)
│ lea rdi, qword [rax + rax*2] ; rdi *= 3 same
│ shl rdi, 5                   ; rdi *= 8 * 4 (8 == sizeof(b2ContactCreateFcn*), 4 == e_typeCount)
│ mov rax, qword [rdi + rsi*8 + b2Contact::s_registers] ; rax = s_registers[type1][type2].createFcn
│ test rax, rax                ; createFcn != nullptr ?
│ je 0x44815f
│ cmp byte [rdi + rsi*8 + 0x50b040], 0 ; s_registers[type1][type2].primary ?
│ je 0x448162
│ mov rdi, r10                 ; prepare indirect call
│ mov esi, r9d
│ jmp rax                      ; call createFcn(fixtureA, indexA, fixtureB, indexB, allocator);

```

You can see that the compiler pretty much deals with this as if the array was 1d, it makes no difference; the code already compiles to efficient multiplications with shifts and adds.

Compiler: clang10. gcc 9.3.0 gives equivalent, but somewhat less elegant, result.

> I think an equivalent approach would be to create two Create implementations with swapped inputs

Yeah that's something that can be done to avoid on if/else pair; dunno about the performance impact due to speculative execution & branch prediction, but someone can give it a shot?

> This isn't Java, there's no VM

With VM I meant the C# Runtime, interpreters/JIT compilers etc. Not a VM in the hardware emulation sense.

> C# gets compiled to IL (Intermediate Language) and on Intel & ARM targets gets compiled Just-In-Time to native code with accelerations supported by the CPU. If you have AVX, it will use AVX. C# can be as fast as C++, if you're careful about how it's used.

For your interest this is the exact same for the JVM. No difference here

**Comment by HughPH** [comment]
> You can see that the compiler pretty much deals with this as if the array was 1d

Yeah, that's what I expected. At first I was thinking the jagged array might have been an issue, but obviously not when it was allocated upfront. You can only allocate the first array upfront in C#, i.e. `ContactRegister[][] s_registers = ContactRegister[e_typeCount][];`, but I might have a look at what happens when it's declared readonly and initialised in the constructor. The old Box2DX port checked if it was null when adding, which leaves a lot of work for the compiler to figure out if the array would ever be changed. There were plenty of public fields & methods too, which would make it even less likely to be optimised.

Getting rid of those `if`s is definitely a micro-optimisation, it probably wouldn't make a noticeable difference in the vast majority of cases.

> this is the exact same for the JVM. No difference here

Fair enough!

I'm going to close this, I think boiling it down, it's just not worth doing.
