### ISSUE TITLE
why Multiply 2 when Compute the cost？

### ISSUE THREAD

**Issue by bellpo** [erincatto/box2d#611]
in b2DynamicTree.cpp at 224 row

// Cost of creating a new parent for this node and the new leaf
float cost = 2.0f * combinedArea;

here why Multiply 2 ? because here only add combinedArea oncetime for add new parent node.

And I think here should be
---------START------------
{

		// Cost of creating a new parent for this node and the new leaf
		float cost =  combinedArea;

		// Minimum cost of pushing the leaf further down the tree
		float inheritanceCost =  (combinedArea - area);

		// Cost of descending into child1
		float cost1;
		if (m_nodes[child1].IsLeaf())
		{
			b2AABB aabb;
			aabb.Combine(leafAABB, m_nodes[child1].aabb);
			cost1 = aabb.GetPerimeter() + inheritanceCost;
		}
		else
		{
			b2AABB aabb;
			aabb.Combine(leafAABB, m_nodes[child1].aabb);
			float oldArea = m_nodes[child1].aabb.GetPerimeter();
			float newArea = aabb.GetPerimeter();
			cost1 = (newArea - oldArea) + inheritanceCost;
		}
}
---------END------------
so compare cost and costLeft , can get the smallest Bounding box for all tree .

**Comment by erincatto** [comment]
I'm guessing the 2 represents the cost of having to visit two children. I agree this is questionable and I think there are other problems with this algorithm. I documented details of improvements here: https://box2d.org/files/ErinCatto_DynamicBVH_Full.pdf

I have a couple more ideas I'd like to try before I bring it to Box2D.
