### ISSUE TITLE
Feature: LiquidFun particle simulation in Box2D

### ISSUE THREAD

**Issue by Hexlord** [erincatto/box2d#612]
**Expected behavior**: erincatto/master provides functionality of particle simulation as in LiquidFun.
**Actual behavior**: it is not the case.
**Proposed solution**: consider revising functionality and code style of https://github.com/erincatto/box2d/compare/master...Hexlord:hexlord/box2d_particles_draft and merging it. 

An ultimate attempt to preserve Erin Catto code style was made, but some inconsistency still remains (footprint of google's code and careless on my part testbeds integration), and could be further improved.

All LiquidFun functionality is integrated, but only some testbeds are partially integrated, and [could be observed on this video](https://www.youtube.com/watch?v=tJKgj1-HZrI&feature=youtu.be).

UnitTest shows no errors, and all Box2D testbeds look visually correct.

Hope this proves useful, looking forward to Box2D growth, happy to see you coming back improving the library!

**Comment by erincatto** [comment]
Google originally inquired about this. I would not take this on because I would be responsible for this feature and I would likely do it differently. I recommend to keep it in your fork and make use of it there.

**Comment by Hexlord** [comment]
> Google originally inquired about this. I would not take this on because I would be responsible for this feature and I would likely do it differently.
That is respectable, I actually agree, but I think the realistic alternative is for this feature to never come. Which might be OK.

> I recommend to keep it in your fork and make use of it there.
Sure. Thanks for taking a look.
