### ISSUE TITLE
[suggestion] Add CMake install support

### ISSUE THREAD

**Issue by uilianries** [erincatto/box2d#622]
Hi!

I would like to propose the `install` method in CMakeLists.txt file. IIRC the version 2.3.1 provides it, but 2.4.0 doesn't. It helps a lot when packaging and distributing Box2D. I can propose a PR.

Regards!

- [ ] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)
- [ ] Consider providing a dump file using b2World::Dump

**Comment by erincatto** [comment]
I take PRs for CMake. I mainly work on Windows where ```install``` is not useful.

**Comment by uilianries** [comment]
I don't think it's related to OS, for instance, I could build Box2D in my CI for any OS and distribute in my company.

**Comment by erincatto** [comment]
2.3.1 had cmake installation scripts that I did not write.
