### ISSUE TITLE
Two Unused Variables in Box2D 2.4.0

### ISSUE THREAD

**Issue by dave-gallagher** [erincatto/box2d#623]
In Box2D 2.4.0 there are two unused variables displaying a compiler warning for each when compiled:

1. https://github.com/erincatto/box2d/blob/4d7757feedc9dd36f64393ae08acfd3b9600ac17/src/dynamics/b2_rope_joint.cpp#L78
2. https://github.com/erincatto/box2d/blob/4d7757feedc9dd36f64393ae08acfd3b9600ac17/src/dynamics/b2_revolute_joint.cpp#L260

I'm unsure if these are meant for future use or if they are left over from past changes.

Thank you for making Box2D and releasing 2.4.0! 😄

**Comment by erincatto** [comment]
Thanks! Definitely left over cruft. Too bad my CI didn't catch these.
#629
