### ISSUE TITLE
Minor resource leak in testbed

### ISSUE THREAD

**Issue by yowidin** [erincatto/box2d#624]
While looking around the `testbed` sources I noticed a minor resource leak in the `GLRenderPoints` class:
Three buffers are allocated [here](https://github.com/erincatto/box2d/blob/master/testbed/draw.cpp#L227):
```
glGenBuffers(3, m_vboIds);
```

But only two are released [here](https://github.com/erincatto/box2d/blob/master/testbed/draw.cpp#L261):
```
glDeleteBuffers(2, m_vboIds);
```

Somehow related to the problem above: since testbed already requires C++11, what is your position on PRs containing only some minor code modernizations for testbed? :)

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)
- [ ] Consider providing a dump file using b2World::Dump

**Comment by erincatto** [comment]
Thanks for the report. Sorry, I don't take PRs for code changes.

For C++11 I only adopted nullptr and override. I like override because it helps find bugs and has no cost. If I had the time, I would consider C99 rather than C++ modernization.

#629
