### ISSUE TITLE
b2ShapeCast throws assert due to accessing witness points on an empty simplex.

### ISSUE THREAD

**Issue by MelvMay-Unity** [erincatto/box2d#625]
When performing a b2ShapeCast with the following b2ShapeCastInput:

![image](https://user-images.githubusercontent.com/5794808/88918725-daa30980-d261-11ea-8500-a4dc2280c5b9.png)

... this line immediately terminates the simplex loop therefore leaving the Simplex empty (count=0) so when the subsequent code tries to access the witness points, it hits the simplex assert.

`while (iter < k_maxIters && b2Abs(v.Length() - sigma) > tolerance)`

v = {x=-0.105458483 y=0.229372352 }
sigma = 0.249999985
tolerance = 0.00249999994
so it becomes (0.00245429575 > 0.00249999994)

**Comment by erincatto** [comment]
Thanks for the detailed report. I think your case should be considered an initial overlap and therefore a miss. In the future if I add broader support for shape cast queries I will probably give an option to check for initial overlap.

#628
