### ISSUE TITLE
b2_weld_joint has ``GetFrequency()`` instead of ``GetStiffness()``

### ISSUE THREAD

**Issue by abakobo** [erincatto/box2d#626]
Discord user "Ardjanusz" has posted the following on discord and was invited to post the issue on github. I post it myself as he doesn't seem to post the issue here.

_I noticed something: b2_weld_joint.h, line 88 method still says GetFrequency and corresponding setter refers to Stiffness its not intentional right?_

thx

**Comment by HughPH** [comment]
Also MouseJoint.h and MouseJoint.cpp

**Comment by erincatto** [comment]
#627
