### ISSUE TITLE
b2_wheel_joint.GetReactionForce doesn't include limit impulse

### ISSUE THREAD

**Issue by wnbittle** [erincatto/box2d#634]
https://github.com/erincatto/box2d/blob/4e8f03d45abaa147e2ee6b5790a7e939d199d1c4/src/dynamics/b2_wheel_joint.cpp#L458

After reading your post on [predictive limits](https://box2d.org/posts/2020/04/predictive-joint-limits/) (big thanks for sharing btw) and trying them out in dyn4j, I found this.  Should the GetReactionForce method in the b2_wheel_joint class include the lower and upper impulse?
```
return inv_dt * (m_impulse * m_ay + (m_springImpulse + m_lowerImpulse + m_upperImpulse) * m_ax);
```

**Comment by erincatto** [comment]
Fixed in #641
