### ISSUE TITLE
Hi, how to 'link' edge shapes in v2.4?

### ISSUE THREAD

**Issue by jcyuan** [erincatto/box2d#648]
my game is an endless 2d platformer, in 2.3 i create (or move the previous) edge shape forward ahead by dynamically change it's `m_nextVertex & m_hasNextVertex` for chain or `m_hasVertex3 & m_vertex3` for edge to achieve road edge recycling.
but in 2.4 they are removed and new `SetOneSided` and `SetTwoSided` provided, what should i do to achieve what i want? (of course take ghost collision into account)
thanks.

**Comment by jcyuan** [comment]
and a question: what is the difference between this two methods?

**Comment by jcyuan** [comment]
actually what confused me is, in v2.3 there is `hasPrevVertex / hasNextVertex / SetNextVertex / SetNextVertex` in it, and i can only set v0 or v3 for the shape, but now only 2 cases you can choose: OneSided (provide all v0 - v3), otherwise TwoSided, am i right?

**Comment by thegrb93** [comment]
I think edge shapes now always have next/prev Vertex and you need to set them via constructor or public methods. The has* stuff was removed.

**Comment by jcyuan** [comment]
and onemore, there is no frequencyhz anymore, it's replaced with stiffness J.C 邮箱：jcyuan.space@gmail.com 签名由 网易邮箱大师 定制 On 09/25/2020 20:35, thegrb93 wrote: I think edge shapes now always have next/prev Vertex and you need to set them via constructor or public methods. The has* stuff was removed. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by thegrb93** [comment]
Yeah, those were replaced too, but there's some new helper functions that let you convert to Stiffness and Damping if needed.

**Comment by erincatto** [comment]
You can just destroy and recreate the shape.

**Comment by jcyuan** [comment]
> You can just destroy and recreate the shape.

hi, if i destroy / recreate repaidly, is this a efficient way? i mean, more efficient than re-use?

**Comment by erincatto** [comment]
Modifying a shape in place is just as expensive as recreate.

**Comment by jcyuan** [comment]
> Modifying a shape in place is just as expensive as recreate. Recreating is likely to be more robust as well.

i got it, thanks so much!
