### ISSUE TITLE
New release with cmake install feature

### ISSUE THREAD

**Issue by marmichalski** [erincatto/box2d#649]
Hi @erincatto! When should we expect a new release with recently added `cmake --install` feature? Would it be a hassle to release it soon? :)

Thanks!

**Comment by erincatto** [comment]
Probably will make a new release after #631 is merged. Still in review.

**Comment by erincatto** [comment]
Done. See https://github.com/erincatto/box2d/releases/tag/v2.4.1

**Comment by marmichalski** [comment]
Thanks! 🎉🥳
