### ISSUE TITLE
Pip install issue

### ISSUE THREAD

**Issue by malisevinc** [erincatto/box2d#650]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)

Hi I can not pip install "Box2D‑2.3.10‑cp39‑cp39‑win_amd64.whl". I get "ERROR: Box2D-2.3.10-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.". And my computer and OS 64 bit architecture

**Comment by erincatto** [comment]
Sorry, pip is not supported by this project.

**Comment by malisevinc** [comment]
How could I install my environment Box2D then. Is there another way to install

**Comment by erincatto** [comment]
Sorry, I know nothing about pip. If you look at this project you can see that it is just a C++ project.

**Comment by malisevinc** [comment]
I found the problem since I am using python version 3.8 it needs to be cp 3.8. I installed with pip to my environment succesfully thnaks anyway
