### ISSUE TITLE
Unresolved External Symbol Error When Using cmake For Visual Studio 2019

### ISSUE THREAD

**Issue by Alsira** [erincatto/box2d#660]
I get an error after building using cmake for this project. The function that the linker cannot find is GetUserData function in the b2Body class. Everything else works fine, but this function breaks my project.

**Comment by erincatto** [comment]
I think you mean b2Body::SetUserData. This function is no longer needed and was removed in #659.

**Comment by flarn2006** [comment]
It's needed if you want code that's more than a couple weeks old to compile without modification. See #663.
