### ISSUE TITLE
GLFW error occured. Code: 65543.

### ISSUE THREAD

**Issue by bigvzhang** [erincatto/box2d#661]
Got the following error when run testbed:
GLFW error occured. Code: 65543. Description: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
Failed to open GLFW g_mainWindow.

Could you help to look into it

**Comment by erincatto** [comment]
Sorry, I don't know anything about this error. Please ask for help on Discord. https://discord.gg/NKYgCBP
