### ISSUE TITLE
Breaking changes in b2MouseJointDef

### ISSUE THREAD

**Issue by ufrshubham** [erincatto/box2d#664]
It seems in v2.4.1, dampingRatio and frequencyHz were removed from b2MouseJointDef. Instead of those two parameters, damping and stiffness have been introduced. I think this change is not documented in breaking changes list. What changes should one make to get old behaviour with new parameters?

**Comment by thegrb93** [comment]
The new freq/damping can be calculated from old values using these.
https://github.com/erincatto/box2d/blob/8815e0963d2c042309ab302fadcea47034f352cb/src/dynamics/b2_joint.cpp#L40-L88

**Comment by ufrshubham** [comment]
> The new freq/damping can be calculated from old values using these.
> https://github.com/erincatto/box2d/blob/8815e0963d2c042309ab302fadcea47034f352cb/src/dynamics/b2_joint.cpp#L40-L88

That worked! Thanks 🤘🏻
