### ISSUE TITLE
box2d doesn't compile on M1 Mac due to outdated version of Doctest

### ISSUE THREAD

**Issue by PatrickHoward** [erincatto/box2d#679]
Hello! I posted this on [Discord a few days ago](https://discord.com/channels/460295137705197568/491287246377582611/820076597473837097) but opening an issue for this might be more suitable.

I've been porting my game engine over to native Apple Silicon and box2d is the only dependency that doesn't compile successfully. It turns out that the testing suite's macro for breaking to a debugger had some inline assembly that was used on Mac. This has been changed as of [Doctest 2.4.1](https://github.com/onqtam/doctest/blob/master/CHANGELOG.md#241-2020-11-04).

My request is to bring box2d's version of Doctest up to at least 2.4.1, essentially bringing support for M1.

**Comment by dadabit** [comment]
me too

**Comment by PatrickHoward** [comment]
Closing this issue since the PR referenced above has been merged into master, thanks! 😄
