### ISSUE TITLE
README cmake install features

### ISSUE THREAD

**Issue by invitus** [erincatto/box2d#686]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)
- [ ] Consider providing a dump file using b2World::Dump

The example currently says to use:
`target_link_libraries(mytarget PRIVATE box2d)`

which was changed from:
`target_link_libraries(mytarget PRIVATE box2d::box2d)`

due to the issue:
https://github.com/erincatto/box2d/issues/647

However, if you use the cmake install feature (as stated by the README), you have to use box2d::box2d.
In the previous issue the install feature was not used, but rather a submodule with a subdirectory to the box2d cmake.

_Originally posted by @invitus in 
https://github.com/erincatto/box2d/issues/647#issuecomment-739920762_

**Comment by erincatto** [comment]
I'm just going to remove this part of the documentation because I am not testing this workflow.
