### ISSUE TITLE
Adjusting Frequency Hertz will weld joints improperly

### ISSUE THREAD

**Issue by KylinLove** [erincatto/box2d#688]
Hello,
During the process of using Box2D, I found some weird phenomena when welding joints adjusted FrequencyHertz. Could you please confirm whether it is a bug?
This is the key code to test the code. When you adjust the number to 20~30, something weird happens。
```
m_hertz = 10.0f; // change to 20.0f~30.0f
```
The test file is as follows:

[weld_joint.cpp.txt](https://github.com/erincatto/box2d/files/6550686/weld_joint.cpp.txt)

appreciated if any help!

**Comment by erincatto** [comment]
Use `b2AngularStiffness` for rotational stiffness.
