### ISSUE TITLE
Box2D 2.4.1 shows version number 2.4.0

### ISSUE THREAD

**Issue by QrtAwb** [erincatto/box2d#696]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)
- [x] Consider providing a dump file using b2World::Dump

It is not a real problem - helped myself:
the actual version of Box2D (2.4.1) still shows '2.4.0'  - see 'b2_settings.cpp' line 30.
Did I overlook something?

**Comment by tpimh** [comment]
Well, 2.4.2 shows 2.4.1... It's okay, I guess.
