### ISSUE TITLE
GLFW error

### ISSUE THREAD

**Issue by kadko** [erincatto/box2d#700]
I build testbed by running build.bat file then I created binaries with generated Visual Studio 17 solution file

When I click testbed.exe I got this error:

```
GLFW error occured. Code: 65543. Description: WGL: OpenGL profile requested but
WGL_ARB_create_context_profile is unavailable
Failed to open GLFW g_mainWindow.
```
![image](https://user-images.githubusercontent.com/991718/141842159-c6df582d-0caf-4d82-850c-3395b24b3eea.png)

**Comment by erincatto** [comment]
I guess your platform is not supported by the version of OpenGL I use. Sorry!
