### ISSUE TITLE
leftover b2Body::SetUserData() declaration

### ISSUE THREAD

**Issue by check-switch-26** [erincatto/box2d#703]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)
- [x] Consider providing a dump file using b2World::Dump

b2Body::SetUserData() definition was removed.
The declaration in b2_body.h at line 382 should be removed as well.

**Comment by erincatto** [comment]
Fixed
