### ISSUE TITLE
b2PolygonShape::Set asserts because of gift wrapping algorithm failing

### ISSUE THREAD

**Issue by simonvanbernem** [erincatto/box2d#728]
I've run into an issue where submitting a non-degenerate, convex polygon to b2PolygonShape::Set will result in the following assert triggering: `b2PolygonShape::set: b2Assert(m < b2_maxPolygonVertices);`. This happens because gift wrapping fails in a way that will lead to vertices being added to the hull more than once. This is the polygon (given as hex values of x and y) which triggered the assert:

        [0].x: 0xC1078533
        [0].y: 0x3F0BAB5E
        [1].x: 0xC0F5B2E8
        [1].y: 0x3F28AF8C
        [2].x: 0xC0E2B14A
        [2].y: 0x3F3E72AE
        [3].x: 0xC0EBC298
        [3].y: 0x402E521E
        [4].x: 0xC1158EA9
        [4].y: 0x401C2F82
        [5].x: 0xC1110602
        [5].y: 0x3EEBD078

A first attempt of Erin to modify the problematic code (the collinearity check) fails for the following polygon:

        [0].x: 0x3F800000
        [0].y: 0xBF800000
        [1].x: 0x3F800000
        [1].y: 0x3F800000
        [2].x: 0xBF800000
        [2].y: 0x3F800000
        [3].x: 0xBF800000
        [3].y: 0xBF800000
        [4].x: 0xBF09F775
        [4].y: 0xBF876E83
        [5].x: 0x3F3787C5
        [5].y: 0xBF81F4D7

I'm willing to help test new fixes, and have also written a tiny fuzzer:

	{
		//the case that initially triggered the assert
		u32 repro_case[12] = {0xC1078533, 0x3F0BAB5E, 0xC0F5B2E8, 0x3F28AF8C,
			0xC0E2B14A, 0x3F3E72AE, 0xC0EBC298, 0x402E521E,
			0xC1158EA9, 0x401C2F82, 0xC1110602, 0x3EEBD078};

		b2PolygonShape shape;
		shape.Set((b2Vec2*) repro_case, 6);

		//We create a box of from {-1,-1} to {1,1}, and add two random vertices between {-1,-1} and {1,-1}
		Vector2 points[6] = {Vector2(1, -1), Vector2(1, 1), Vector2(-1, 1),
			Vector2(-1, -1), Vector2(0, -1), Vector2(0, -1)};

		for(int i = 0; i < 1000; i++){
			//game_biased_random generates random floats in the given interval
			points[4].x = -game_biased_random(0.3f, 0.8f);
			points[4].y = -(1 + game_biased_random(0.001f, 0.1f));
			do{
				points[5].x = game_biased_random(0.3f, 0.8f);
				points[5].y = -(1 + game_biased_random(0.001f, 0.1f));
			}
			while(robust_get_point_orientation_in_relation_to_line(points[3], points[5], points[4]) < 0 ||
				robust_get_point_orientation_in_relation_to_line(points[4], points[0], points[5]) < 0);
			// ensure the polygon is not concave. a result of < 0 means that arg2 is to the right of arg0->arg1.
			// The robust check is based on stable predicates by Jonathan Shewchuk
			// (https://www.cs.cmu.edu/~quake/robust.html)
                        // robust_get_point_orientation_in_realtion_to_line is just a call to orient2d from predicates.c with
                        // the return value negated.

			shape.Set((b2Vec2*) points, 6);
		}
	}

**Comment by erincatto** [comment]
Fixed in #735

**Comment by erincatto** [comment]
Fixed in #735
