### ISSUE TITLE
Warmstart GJK fails

### ISSUE THREAD

**Issue by NStenum** [erincatto/box2d#734]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)
- [ ] Consider providing a dump file using b2World::Dump

**Comment by NStenum** [comment]
Getmetric for 3 points may return a negative number which will make readcache reset simplex. 
Suggest using sqr values which will speedup getmetric for 2 points.
Also, when resetting simplex -  keep first simplexvertex instead of picking new arbitrary points

**Comment by erincatto** [comment]
Closing out v2 issues since it is no longer supported.
