### ISSUE TITLE
pip install box2d on Windows with Python 3.10 not working

### ISSUE THREAD

**Issue by premsaggar** [erincatto/box2d#740]
Hello everyone, how do we install box2d on Windows with pip on Python 3.10? I've followed the get it with Microsoft build tools links but I've been unable to get box2d installed. Can it be done with Python 3.10? Thanks for your help.

**Comment by erincatto** [comment]
Sorry, no Python support here, just C++. Try the box2d discord: https://discord.gg/YRUpfKvF
