### ISSUE TITLE
Full Bounce Error

### ISSUE THREAD

**Issue by quinton-ashley** [erincatto/box2d#752]
Hi I'm wondering if this same error occurs in c++ Box2D? If so could the issue be fixed?

https://github.com/piqnt/planck.js/issues/234

Also thank you for your incredible physics library!

**Comment by DaProGenius** [comment]
Thank you for the opportunity to be able to be apart or something special

**Comment by erincatto** [comment]
Closing out v2 issues since it is no longer supported.
