### ISSUE TITLE
Double free crash on b2Array_Grow

### ISSUE THREAD

**Issue by onehundredfeet** [erincatto/box2d#767]
Make sure these boxes are checked before submitting your issue - thank you!

I'm getting a crash on b2Array_Grow.  The capacity of the array coming in is 0 and I'm getting a double free error.  I'm going to continue debugging and see if I can figure it out.  But in case it's obvious to anyone here I wanted to put this up.

- [X ] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)
- [X] Consider providing a dump file using b2World::Dump

**Comment by onehundredfeet** [comment]
It seems to be when it's pushing an event.  The array that gets passed in has already been freed on the second push.

**Comment by onehundredfeet** [comment]
found the bug.  Preparing a PR.  It was 

```
if (hit == true)
				{
					event.normal = contactSim->manifold.normal;

					b2CheckId(world->shapeArray, contactSim->shapeIdA);
					b2CheckId(world->shapeArray, contactSim->shapeIdB);
					b2Shape* shapeA = world->shapeArray + contactSim->shapeIdA;
					b2Shape* shapeB = world->shapeArray + contactSim->shapeIdB;

					event.shapeIdA = (b2ShapeId){shapeA->id + 1, world->worldId, shapeA->revision};
					event.shapeIdB = (b2ShapeId){shapeB->id + 1, world->worldId, shapeB->revision};

					b2Array_Push(events, event);
				}
				```

**Comment by onehundredfeet** [comment]
https://github.com/erincatto/box2c/pull/166

**Comment by erincatto** [comment]
This was fixed. Thanks for the report!
