### ISSUE TITLE
cmake configure succeeds, but the build later fails: fatal error: 'TaskScheduler.h' file not found

### ISSUE THREAD

**Issue by yurivict** [erincatto/box2d#771]
- [x] Ask for help on [discord](https://discord.gg/NKYgCBP)
- [x] Consider providing a dump file using b2World::Dump

The file TaskScheduler.h isn't included into the project, and it also isn't searched by cmake.

Version: 3.0.0
clang-18
FreeBSD 14.1

**Comment by erincatto** [comment]
Are you trying to build just the library or the samples/tests/benchmark apps? Only the latter make use of enkiTS.
