### ISSUE TITLE
Box2D v2.4.2 version is wrong (set to 2.4.1)

### ISSUE THREAD

**Issue by ensisoft** [erincatto/box2d#778]
Final release v. 2.4.2 of Box2D seems to have version 2.4.1 in the b2_settings.cpp

https://github.com/erincatto/box2d/blob/v2.4.2/src/common/b2_settings.cpp#L30

**Comment by erincatto** [comment]
Sorry, I don't think it is worth to fix this. I'm not supporting older versions of Box2D. This last tag was done as a convenience to users who are not ready to upgrade.
