### ISSUE TITLE
3.0.0 does not install headers and cmake files like 2.4.2

### ISSUE THREAD

**Issue by chenrui333** [erincatto/box2d#781]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] Ask for help on [discord](https://discord.gg/NKYgCBP)
- [ ] Consider providing a dump file using b2World::Dump

----

I am trying to run the 3.0.0 release build, but ended up finding that it does not install box2d headers and cmake configs like 2.4.2, any ideas?

**Comment by erincatto** [comment]
Fixed in #783
