### ISSUE TITLE
API stuff from Melvyn

### ISSUE THREAD

**Issue by erincatto** [erincatto/box2d#791]
I'm curious about the b2DebugDraw::DrawCapsule function; will that be staying? I see it's only called from the test-bed currently.

API request Would it be possible to have the respective getters added for the following?
B2_API void b2World_EnableSleeping( b2WorldId worldId, bool flag );
B2_API void b2World_EnableContinuous( b2WorldId worldId, bool flag );
B2_API void b2World_SetRestitutionThreshold( b2WorldId worldId, float value );
B2_API void b2World_SetHitEventThreshold( b2WorldId worldId, float value );
 
Another thing, it would be great to be able to ask if the world is currently locked as opposed to hitting an assert which then begs the question if this should be an atomic flag? The atomics I'm less bothered about, access to the flag would be great though.

**Comment by MelvMay-Unity** [comment]
[issue_791.patch](https://github.com/user-attachments/files/16910409/issue_791.patch)
In-case it helps, I know you're busy!

**Comment by erincatto** [comment]
Implemented in #787
