### ISSUE TITLE
Redefinition of _CRT_SECURE_NO_WARNINGS macro

### ISSUE THREAD

**Issue by DDeimos** [erincatto/box2d#800]
Hi!
There are several sources with `#define _CRT_SECURE_NO_WARNINGS`. I believe there should be `#ifdef` first for projects which have already defined the macro. In my case I get a lot of warnings because I defined the macro in my project settings to suppres `GLFW` warnings. I could workaround it, but I think that `#ifdef` would be better in any case.

**Comment by erincatto** [comment]
Fixed in #804
