### ISSUE TITLE
Please provide 3.1 changelog

### ISSUE THREAD

**Issue by Clemapfel** [erincatto/box2d#801]
The current master is ahead of the last release, and 3.1 introduced breaking changes, such as renaming `SmoothSegment` to `ChainSegment`, and `b2MakeOffsetBox`s signature changing.

Is there a list of all changes so I can migrate from 3.0 to 3.1? Also a 3.1 release or pre-release should be created, github has a feature to compare releases, but without a release I currently have to sift through all commits to see what exactly changed.

**Comment by erincatto** [comment]
It will be a while before 3.1 is ready. My standard practice is to work on main and not update documentation until the next release.

I only recommend working off main if you are comfortable with this practice. There is a tag and release for 3.0 otherwise.
