### ISSUE TITLE
Collision of 3.0 file names

### ISSUE THREAD

**Issue by DDeimos** [erincatto/box2d#805]
Hi!
You had unique `b2` prefix for all source file names in 2.4.1 and you removed this unique prefix with the 3.0 release. Is there any particular reason for this?
The reason I ask is because this prefix helped to avoid file name collisions. Especially, when you add source files directly to an IDE project. Do you have any plans to add some prefix in future?

**Comment by HughPH** [comment]
Why don't you add them to a subdirectory?

**Comment by erincatto** [comment]
The previous file name prefix didn't seem to follow open source conventions and it is a bit noisy. The only problems I've seen with dropping prefixes is unity builds.

But yeah, for an IDE I recommend to put box2d into a separate folder/static library project.

**Comment by DDeimos** [comment]
> Why don't you add them to a subdirectory?
Because I don't use CMake and Visual Studio compiles all obj-files to the same directory.
> The previous file name prefix didn't seem to follow open-source conventions and it is a bit noisy.
I see. I'll think about either using CMake or compiling Box2D to a static library. Thanks for the answer.
Would you prefer me to close the issue?
