### ISSUE TITLE
Contact normal in b2ContactBeginTouchEvent

### ISSUE THREAD

**Issue by abria** [erincatto/box2d#806]
It would be very useful to add contact normal into `b2ContactBeginTouchEvent`, like `b2ContactHitEvent` already has. 

I need to implement the collision logic based on the collision normal. If my understanding is correct, currently I have to use `b2Shape_GetContactData()` and do a linear search for the targeted collision between A and B. Is there a more efficient method?

**Comment by erincatto** [comment]
I added the entire contact manifold to the begin touch event in #808.
