### ISSUE TITLE
Feature Request: a no-relative-rotation joint

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erincatto/Box2D#81]
```
which make the relative rotation of two bodies unchanged, but has no 
limits on x and y axises.
```

Original issue reported on code.google.com by `Tapir....@gmail.com` on 10 Feb 2010 at 4:17

**Comment by erincatto** [comment]
I'm guessing the original request is really for some way to prevent a body from rotating. I would approach this by setting the inverse inertia tensor to zero. However, this could open up a lot of issues with assumptions throughout the engine.  Punting.
