### ISSUE TITLE
box2d/3.0.0: error: loop not vectorized

### ISSUE THREAD

**Issue by skhaz** [erincatto/box2d#832]
I am having a problem only when compiling box2d with `emsdk`

```
/home/runner/.conan2/p/b/box2d5931abb0d273d/b/src/src/contact_solver.c:865:6: error: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
...
Several similar erros
```

See https://github.com/carimbolabs/carimbo/actions/runs/11643393796/job/32424090261

**Comment by skhaz** [comment]
Reference https://github.com/conan-io/conan-center-index/pull/25815#discussion_r1828008505

**Comment by erincatto** [comment]
It seems they are targeting the 3.0.0 tag. I believe these issues are fixed in main.

**Comment by erincatto** [comment]
I just tested building main using emsdk on WSL and it works fine.
