### ISSUE TITLE
Box2D 3.0.0 compilation error with Visual Studio

### ISSUE THREAD

**Issue by Wuming9472** [erincatto/box2d#836]
I am experiencing a problem that prevents me from compiling box2d code with Visual Studio 2022 17.11.5 and an AMD64 architecture.
I report the error below:

`Error: C2440	Description: 'initializing': cannot convert from 'const ImFontGlyph *' to 'ImFontGlyph *'	Project: samples	File: sample_benchmark.cpp	Line:1329`

`Error:E0144	Description:" a value of type "const ImFontGlyph *" cannot be used to initialize an entity of type "ImFontGlyph *"	Project:  samples	File: sample_benchmark.cpp	Line:1329	`

**Comment by erincatto** [comment]
This should be fixed on main.
