### ISSUE TITLE
gcc-730 32-bit compile error

### ISSUE THREAD

**Issue by sdragonx** [erincatto/box2d#853]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] Ask for help on [discord](https://discord.gg/NKYgCBP)
- [ ] Consider providing a dump file using b2World::Dump

ver 3.0, 64-bit is well.
![2024-12-06_214508](https://github.com/user-attachments/assets/8ec015ba-10ee-418c-9f34-a4631deed520)

**Comment by sdragonx** [comment]
The current C++base libraries tend to follow higher versions of the C++standard, which may result in decreased compatibility.

**Comment by erincatto** [comment]
What device are you targeting?

**Comment by erincatto** [comment]
Closing due to no response.
